"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export const LanguageContext = createContext();

export const translations = {
    fr: {
        // Club Request Modal
        errorLoadingMembers: "Impossible de charger les membres.",
        errorDuplicateRole: "Un même membre ne peut pas occuper deux postes dans le bureau. Veuillez corriger votre sélection.",
        errorCompleteFields: "Veuillez remplir tous les champs et sélectionner un membre pour chaque poste.",
        errorSubmitRequest: "Une erreur est survenue lors de l'envoi de la demande.",
        clubRequestTitle: "Demande d'Activité de Club",
        requestSubmittedSuccess: "Demande soumise avec succès !",
        requestSubmittedDesc: "Votre demande a bien été envoyée au bureau national pour approbation. Vous serez notifié dès qu'elle sera traitée.",
        allMembersMustBeValid: "Tous les membres du bureau ajoutés ci-dessous doivent obligatoirement être adhérents en cours de validité pour cette saison associative.",
        activityLocation: "Lieu d'Activité",
        clubEmailText: "Email du Club",
        suggestedPassword: "Mot de passe suggéré",
        vicePresident: "Vice-Président",
        secretaryGeneral: "Secrétaire Général",
        hrManager: "Responsable RH",
        eventsManager: "Responsable des Événements",
        mediaManager: "Responsable Média",
        selectMemberMenu: "-- Sélectionner un adhérent --",
        submitRequest: "Soumettre la demande",

        // ATA Waves
        ataWaves: "ATA Waves",
        latestEpisodes: "Dernières Émissions",
        episodesCount: "émission(s)",
        noEpisodes: "Aucune émission disponible pour le moment.",
        contentNotAvailable: "Contenu Non Disponible",
        pageNotPublished: "La page ATA Waves n'est pas publiée en ce moment.",
        video: "Vidéo",
        by: "Par",
        publishedOn: "Publié le",
        unsupportedPlayer: "Lecteur non supporté pour cette plateforme",
        openVideoDirectly: "Cliquez sur le bouton ci-dessous pour visionner l'émission directement sur la plateforme d'origine.",
        openVideoBtn: "Ouvrir la vidéo",
        teamAta: "Équipe ATA",

        // Navbar
        home: "Accueil",
        about: "À propos",
        clubs: "Clubs",
        bestOff: "Best Off",
        contact: "Contact",
        games: "Espace Jeux",
        dashboard: "Tableau de Bord",
        connexion: "Connexion",
        signup: "S'inscrire",
        logout: "Se déconnecter",
        installApp: "Installer l'App",

        // Auth
        loginTitle: "Connexion",
        signupTitle: "S'inscrire",
        welcomeBack: "Heureux de vous revoir !",
        accountCreatedSuccess: "Votre compte a été créé avec succès. Veuillez vous connecter.",
        email: "Email",
        password: "Mot de passe",
        forgotPassword: "Mot de passe oublié ?",
        logInProgress: "Connexion...",
        loginBtn: "Se connecter",
        noAccountYet: "Pas encore de compte ?",
        joinAta: "Rejoignez ATA",
        createAccountDesc: "Créez votre compte membre et participez à l'aventure",
        confirmPassword: "Confirmer mot de passe",
        passwordsDontMatch: "Les mots de passe ne correspondent pas.",
        signupProgress: "Création en cours...",
        signupNotice: "Note: Votre compte devra être approuvé par un administrateur avant de pouvoir accéder à toutes les fonctionnalités.",
        chooseClub: "Choisir un club",
        selectFavoriteClub: "Sélectionnez votre club favori",
        alreadyHaveAccount: "Déjà un compte ?",
        loginAction: "Se connecter",
        signupAction: "S'inscrire",
        forgotPasswordTitle: "Mot de passe oublié",
        forgotPasswordSubtitle: "Entrez votre adresse email pour recevoir un lien de réinitialisation.",
        sendResetLink: "Envoyer le lien",
        sendingLink: "Envoi en cours...",
        backToLogin: "Retour à la connexion",
        newPasswordTitle: "Nouveau mot de passe",
        newPasswordSubtitle: "Entrez votre nouveau mot de passe ci-dessous.",
        resetPasswordBtn: "Réinitialiser le mot de passe",
        resettingBtn: "Réinitialisation...",
        invalidToken: "Jeton de réinitialisation invalide ou manquant.",
        requestNewLink: "Demander un nouveau lien.",
        resetSuccessRedirect: "Votre mot de passe a été réinitialisé. Redirection vers la page de connexion...",
        
        // Recruitment
        recruitmentTitle: "📢 Remarque : Statut de la Période d'Inscription",
        recruitmentDays: "Il reste",
        recruitmentDaysAfter: "jour(s) avant la fermeture des inscriptions.",
        recruitmentClosesAt: "(Clôture prévue le",
        recruitmentOpen: "La période d'inscription pour cette saison est actuellement ouverte.",
        registrationClosedTitle: "Inscriptions Fermées",
        registrationClosedMessage: "La période d'inscription pour cette saison n'est pas ouverte actuellement.",
        backToHome: "Accéder à l'accueil",

        // Home
        brandName: "Touches D'Art",
        heroTitle: "Exprimez votre créativité avec",
        heroSubtitle: "Association culturelle, artistique et académique. Rejoignez une communauté passionnée et participez à des projets innovants.",
        discoverClubs: "Découvrir les clubs",
        joinUs: "Rejoindre",
        accessDashboard: "Accéder au Dashboard",
        newsEvents: "Actualités & Événements",
        upcomingActivities: "Les événements de nos clubs à ne pas manquer.",
        featured: "À la une",
        artCulture: "Art & Culture",
        artCultureDesc: "Des ateliers et événements pour promouvoir l'art sous toutes ses formes.",
        community: "Communauté",
        communityDesc: "Un réseau d'étudiants et de passionnés unis par la créativité.",
        excellence: "Excellence",
        excellenceDesc: "Des projets académiques et artistiques de haut niveau.",
        ourClubs: "Nos Clubs",
        viewPage: "Voir la page",
        noDescription: "Aucune description disponible pour le moment.",
        learnMore: "En savoir plus",

        // Best Off
        bestOffSubtitle: "Explorez les moments marquants et les réalisations exceptionnelles de la communauté Touches D'Art.",
        bestOffEmpty: "La galerie est en cours de préparation. Revenez bientôt !",

        // Search
        searchPlaceholder: "Rechercher sur la page...",
        results: "résultats",

        // Clubs
        ourClubsTitle: "Nos Clubs",
        ourClubsSubtitle: "Découvrez la richesse de nos pôles d'activité. Il y a forcément un club fait pour vous.",
        noClubs: "Aucun club n'est encore enregistré. Revoyez l'espace Administration.",
        clubATA: "Club ATA",
        backToClubs: "Retour aux clubs",
        aboutClub: "À propos du club",
        followUs: "Suivez-nous",
        activeMembers: "Membres Actifs",
        realTime: "Temps réel",
        birthdayTitle: "C'est la fête ! 🎂",
        birthdaySubtitle: "Joyeux anniversaire à notre membre exceptionnel :",
        birthdaySubtitlePlural: "Joyeux anniversaire à nos membres exceptionnels :",
        birthdaySubtitleDesc: "Célébrons ensemble nos membres exceptionnels !",
        noBirthdayToday: "Aucun anniversaire aujourd'hui !",
        comeBackTomorrow: "Revenez demain pour célébrer nos membres.",
        itsTheirDay: "Aujourd'hui, c'est son jour !",
        president: "Président",
        nationalBoardMember: "Membre Bureau National",
        eventsFormations: "Événements & Formations",
        photoGallery: "Galerie Photos",
        videosCreations: "Vidéos & Réalisations",
        testimonialsTitle: "Avis & Témoignages",
        leaveReview: "Laisser un avis",
        close: "Fermer",
        yourName: "Votre nom (Optionnel si membre)",
        fullName: "Nom complet",
        rating: "Note",
        yourMessage: "Votre message",
        shareExperience: "Partagez votre expérience...",
        sendReview: "Envoyer mon avis",
        reviewSuccess: "Merci ! Votre avis a été envoyé et sera visible après validation.",
        noReviews: "Aucun avis pour le moment. Soyez le premier !",
        anonymous: "Anonyme",

        // About
        aboutTitle: "Touches D'Art",
        aboutDesc: "\"Touches d'Art\" est une association culturelle qui accueille un groupe de jeunes créatifs dotés de talents variés, tels que l'organisation d'événements, l'animation de publics, le journalisme et les médias, la peinture, le chant et bien d'autres formes d'art et de talents.",
        objectivesTitle: "Objectifs de l'Association",
        obj1: "Contribuer à ancrer les valeurs du bénévolat et de l'esprit d'initiative dans les milieux jeunes.",
        obj2: "Soutenir le tourisme intérieur et promouvoir les sites touristiques.",
        obj3: "Promouvoir les monuments historiques en Tunisie en coordination avec les responsables.",
        domainsTitle: "Nos Domaines d'Activité",
        domain1Title: "Domaine Culturel & Artistique",
        domain1Desc: "Le club se concentre sur l'aspect culturel, particulièrement chez les jeunes, en organisant des activités culturelles visant à enrichir la scène culturelle et à apporter des touches artistiques.",
        domain2Title: "Domaine Social & Éducatif",
        domain2Desc: "Nous créons une cohérence entre le nom et le thème de l'association en favorisant l'apprentissage collectif et le partage de savoir-faire entre les membres.",
        domain3Title: "Domaine Récréatif",
        domain3Desc: "Des moments de détente pour les membres, tout en ouvrant nos portes au public à travers l'organisation d'activités diverses et de sorties récréatives.",
        valuesTitle: "Nos Valeurs",
        value1Title: "Excellence",
        value1Desc: "Proposer des contenus et événements de haute qualité académique et artistique.",
        value2Title: "Passion",
        value2Desc: "Encourager chacun à vivre pleinement ses centres d'intérêt et à les partager.",
        value3Title: "Innovation",
        value3Desc: "Constamment repousser les limites en fusionnant art traditionnel et modernité.",
        boardTitle: "Bureau National",
        pollsTitle: "Votre avis nous intéresse",

        // Contact
        contactTitle: "Contactez-nous",
        contactSubtitle: "Une question, une proposition ou une réclamation ? Écrivez-nous.",
        subject: "Sujet",
        selectSubject: "Sélectionnez un sujet",
        info: "Demande d'information",
        partnership: "Proposition de partenariat",
        complaint: "Réclamation",
        other: "Autre",
        message: "Message",
        messagePlaceholder: "Votre message...",
        yourEmail: "Votre Email",
        send: "Envoyer le message",
        sending: "Envoi...",
        success: "Message envoyé avec succès ! Nous vous répondrons bientôt.",

        // Modal
        clubLabel: "Club",
        noDescAvailable: "Pas de description disponible.",
        featuredPhoto: "Photo à la Une",
        eventVideo: "Vidéo de l'événement",
        photoAlbum: "Album Photo",
        participate: "Participer / Voir plus",

        // Polls
        resultsLabel: "Résultats",
        votesLabel: "voix",
        thanksParticipation: "Merci pour votre participation !",
        voteBtn: "Voter",
        votingBtn: "Envoi...",
        multipleChoices: "Plusieurs choix autorisés",
        singleChoice: "Un seul choix possible",
        membersOnly: "Membres uniquement",
        openToAll: "Ouvert à tous",
        voteError: "Une erreur est survenue lors du vote",

        // Dashboard
        dashboardTitle: "Tableau de Bord",
        dashboardOverview: "Vue d'ensemble",
        myProfile: "Mon Profil",
        notifications: "Notifications",
        messaging: "Messagerie",
        memberVoice: "Voix des Membres",
        voiceManagement: "Gestion Voix Membres",
        demandsReclamations: "Demandes & Réclamations",
        users: "Utilisateurs",
        clubsManagement: "Gestion Clubs",
        membersManagement: "Gestion Membres",
        nationalBoard: "Bureau National",
        partners: "Partenaires",
        contents: "Contenus",
        actionsModeration: "Modération Actions",
        pollsModeration: "Modération Sondages",
        actionsManagement: "Gestion Actions",
        generalSettings: "Paramètres Généraux",
        myClub: "Mon Club",
        pageSettings: "Paramètres Page",
        contentsEvents: "Contenus & Événements",
        actionsAttendance: "Actions & Présences",
        reviewsTestimonials: "Avis & Témoignages",
        polls: "Sondages",
        totalActions: "Actions Totales",
        recentActivity: "Activité Récente",
        engagementPerformance: "Engagement & Performance",
        points: "pts",
        closeProfile: "Fermer le profil",
        noActivityData: "Données d'activité insuffisantes",
        clubNews: "Actualités des Clubs",
        next10Days: "(Prochains 10 jours)",
        warningTitle: "Avertissement Officiel",
        agrementTitle: "Agrément et Activité des Clubs",
        agrementBtn: "Faire une demande d'activité",
        agrementDesc1: "Il est strictement interdit de créer ou de poursuivre toute activité d'un club sous la tutelle de l'Association Touches D'Art sans soumettre une demande officielle et obtenir l'accord préalable de l'Association. La demande doit obligatoirement être créée sur le site. Elle doit préciser le lieu d'activité ainsi que la liste des membres du bureau du club choisi par une liste déroulante de membres pour chaque responsabilité : Président, Vice-Président, Secrétaire Général, Responsable des Ressources Humaines, Responsable des Événements et Responsable de la Communication. Tous les membres du bureau doivent obligatoirement être ",
        agrementDesc2: "adhérents en cours de validité",
        agrementDesc3: " auprès de l'Association. La demande doit être renouvelée et faire l'objet d'une approbation officielle au début de chaque saison associative. Toute activité exercée sans respecter ces conditions est considérée comme non autorisée et ne représente pas l'Association Touches D'Art.",
        memberVoiceTitle: "Voix des Membres",
        memberVoiceSubtitle: "Un espace sécurisé pour partager vos problèmes, préoccupations ou remarques. Votre voix compte pour nous.",
        yourMessageLabel: "Votre message / description du problème",
        messagePlaceholderVoice: "Décrivez ici ce que vous souhaitez nous dire...",
        submissionMode: "Comment souhaitez-vous soumettre ce message ?",
        anonymousMode: "Anonyme",
        identifiedMode: "Identifié",
        messageSentSuccess: "Merci pour votre partage",
        messageSentDesc: "Votre message a été transmis en toute confidentialité. Nous accordons une grande importance à votre bien-être au sein de Touches D'Art.",
        sendAnother: "Envoyer un autre message",
        sendingVoice: "Envoi en cours...",
        sendMyMessage: "Envoyer mon message",
        adminNotice: "Votre message sera traité par l'administration et le président de votre club (si applicable).",
        profileTitle: "Mon Profil",
        firstName: "Prénom",
        lastName: "Nom",
        phoneWhatsApp: "Téléphone / WhatsApp",
        birthDate: "Date de Naissance",
        favoriteClub: "Club Favori",
        selectClub: "Sélectionner un club",
        saveChanges: "Sauvegarder les modifications",
        profileUpdated: "Profil mis à jour avec succès !",
        membershipCard: "Ma Carte Membre",
        security: "Sécurité",
        newPassword: "Nouveau mot de passe",
        confirmPassword: "Confirmer le mot de passe",
        updateError: "Erreur lors de la mise à jour.",
        serverError: "Erreur serveur.",
        loadingProfile: "Chargement du profil...",
        sessionExpired: "Votre session a expiré ou est invalide. Veuillez vous reconnecter.",
        errorLoadingProfile: "Erreur lors du chargement du profil.",
        searchMember: "Rechercher un membre...",
        noUserFound: "Aucun utilisateur trouvé",
        startConversation: "Commencez la conversation avec",
        typeMessage: "Tapez votre message...",
        internalMessaging: "Messagerie Interne",
        selectMemberToChat: "Sélectionnez un membre dans la liste pour démarrer une discussion.",
        seen: "Vu",
        sent: "Envoyé",
        reclamationsTitle: "Demandes & Réclamations (Visiteurs)",
        noReclamations: "Aucune réclamation ou demande de partenariat pour le moment.",
        subjectInfo: "Demande Info",
        subjectPartnership: "Proposition Partenariat",
        subjectComplaint: "Réclamation / Plainte",
        newBadge: "NOUVEAU",
        markAsRead: "Marquer comme lu",
        delete: "Supprimer",
        receivedOn: "Reçu le",
        replyByEmail: "Répondre par Email",
        usersManagementTitle: "Gestion des Utilisateurs",
        selectAll: "Tout sélectionner",
        deselectAll: "Tout désélectionner",
        exportExcel: "Exporter Excel",
        member: "Membre",
        role: "Rôle",
        payment: "Paiement",
        phone: "Téléphone",
        status: "Statut",
        paid: "Payé",
        notPaid: "Non payé",
        pending: "En attente",
        approved: "Approuvé",
        rejected: "Refusé",
        confirmDeleteUser: "Supprimer cet utilisateur ?",
                pendingActivityRequests: "Demandes d'Activité en Attente",
        activeClubs: "Clubs Actifs",
        hiddenFromSite: "Masqué du site",
        clubActive: "Club Actif",
        clubInactive: "Club Inactif",
        deactivate: "Désactiver",
        reactivate: "Réactiver",
        confirmReactivateClub: "Voulez-vous réactiver le club \"{clubName}\" ? Ses membres non désactivés individuellement par l'admin seront réactivés.",
        confirmDeactivateClub: "Voulez-vous désactiver le club \"{clubName}\" ? Tous ses membres seront aussi désactivés.",
        confirmApproveRequest: "Accepter la demande pour \"{clubName}\" ?\n\n✅ Cela va :\n- Créer la page du club\n- Créer le compte avec le rôle \"club\"\n- Attribuer 5 points de score au club\n- Assigner les postes du bureau aux membres",
        confirmRejectRequest: "Refuser la demande pour \"{clubName}\" ?\n\nLe club ne sera pas créé.",
        acceptAndCreate: "✅ Accepter & Créer",
        rejectBtn: "❌ Refuser",
        processing: "⏳ Traitement...",
        processingShort: "⏳ ...",
        confirmShowClub: "Réafficher \"{clubName}\" dans la liste publique des clubs ?",
        confirmHideClub: "Masquer \"{clubName}\" de la liste publique des clubs ?\n\nLe club ne sera pas supprimé, juste invisible sur le site.",
        proposedBureau: "Bureau proposé :",
        waiting: "En attente",
        pendingActivityRequests: "Demandes d'Activité en Attente",
        activeClubs: "Clubs Actifs",
        hiddenFromSite: "Masqué du site",
        clubActive: "Club Actif",
        clubInactive: "Club Inactif",
        deactivate: "Désactiver",
        reactivate: "Réactiver",
        confirmReactivateClub: "Voulez-vous réactiver le club \"{clubName}\" ? Ses membres non désactivés individuellement par l'admin seront réactivés.",
        confirmDeactivateClub: "Voulez-vous désactiver le club \"{clubName}\" ? Tous ses membres seront aussi désactivés.",
        confirmApproveRequest: "Accepter la demande pour \"{clubName}\" ?\n\n✅ Cela va :\n- Créer la page du club\n- Créer le compte avec le rôle \"club\"\n- Attribuer 5 points de score au club\n- Assigner les postes du bureau aux membres",
        confirmRejectRequest: "Refuser la demande pour \"{clubName}\" ?\n\nLe club ne sera pas créé.",
        acceptAndCreate: "✅ Accepter & Créer",
        rejectBtn: "❌ Refuser",
        processing: "⏳ Traitement...",
        processingShort: "⏳ ...",
        confirmShowClub: "Réafficher \"{clubName}\" dans la liste publique des clubs ?",
        confirmHideClub: "Masquer \"{clubName}\" de la liste publique des clubs ?\n\nLe club ne sera pas supprimé, juste invisible sur le site.",
        proposedBureau: "Bureau proposé :",
        waiting: "En attente",
clubsManagementTitle: "Gestion des Clubs",
        newClub: "Nouveau Club",
        editClub: "Modifier le Club",
        confirmDeleteClub: "Supprimer ce club ?",
        clubName: "Nom du Club",
        slugLabel: "Slug (url, ex: club-theatre)",
        description: "Description",
        addressLocal: "Adresse / Local",
        socialLinks: "Réseaux Sociaux",
        selectPresident: "Sélectionner un Président",
        activeMembersLabel: "Membres Actifs",
        partnerReviewsLabel: "Avis Partenaires",
        coverImage: "Image de Couverture",
        chooseImage: "Choisir une image",
        uploading: "Importation...",
        update: "Mettre à jour",
        createClub: "Créer le Club",
        manageMyPage: "Gérer ma page",
        identityDescription: "Identité & Description",
        clubDescription: "Description du club",
        activeMembersOfMonth: "Membres Actifs du Mois",
        selectMembersToHighlight: "Sélectionnez les membres à mettre en avant ce mois-ci.",
        addMember: "Ajouter un membre",
        chooseMember: "Choisir un membre",
        roleOptional: "Rôle (optionnel)",
        period: "Période",
        noFeaturedMembers: "Aucun membre mis en avant pour le moment.",
        reviewsTestimonials: "Avis & Témoignages",
        addReview: "Ajouter un avis",
        author: "Auteur",
        organization: "Organisation",
        reviewContent: "Contenu de l'avis",
        saveAllChanges: "Sauvegarder tous les changements",
        savingChanges: "Enregistrement en cours...",
        changesSaved: "Modifications enregistrées !",
        loadingMyClub: "Chargement de votre club...",
        noClubAssigned: "Aucun club ne vous a été assigné par l'administrateur.",
        selectMember: "-- Sélectionner --",
        actionsAttendance: "Actions & Présences",
        newAction: "Nouvelle Action",
        noActionsFound: "Aucune action trouvée. Créez-en une pour commencer.",
        addFirstAction: "Ajouter ma première action",
        confirmDeleteAction: "Êtes-vous sûr de vouloir supprimer cette action ?",
        manageAttendance: "Gérer la présence",
        addAction: "Ajouter une Action",
        actionTitle: "Titre de l'action",
        startDateLabel: "Date de début",
        startTimeLabel: "Heure locale",
        creating: "Création...",
        createAction: "Créer l'action",
        actions: "Actions",
        attendanceList: "Liste de Présence",
        present: "Présent",
        remark: "Remarque",
        noMemberFoundClub: "Aucun membre trouvé pour ce club.",
        detailsUpdated: "Détails mis à jour !",
        attendanceUpdated: "Présences mises à jour avec succès !",
        actionNotFound: "Action introuvable.",
        errorLoadingAction: "Erreur lors du chargement de l'action.",
        addRemark: "Ajouter une remarque...",
        contentsEventsTitle: "Contenus & Événements",
        noContentPublished: "Aucun contenu publié pour le moment.",
        editContent: "Modifier le contenu",
        newContent: "Nouveau Contenu",
        type: "Type",
        event: "Événement",
        formation: "Formation",
        photoGalleryLabel: "Photo / Galerie",
        videoYoutube: "Vidéo (YouTube, Instagram, Facebook, TikTok)",
        announcement: "Annonce",
        galleryPhotos: "Galerie Photos",
        imagesImported: "image(s) importée(s)",
        clearAll: "Vider tout",
        noPhotoSelected: "Aucune photo sélectionnée",
        videoUrl: "URL Vidéo (YouTube, Instagram, Facebook, TikTok)",
        externalLink: "Lien externe",
        submitForValidation: "Soumettre à validation",
        contentUpdated: "Contenu mis à jour !",
        contentSubmitted: "Contenu soumis avec succès !",
        uploadFailed: "L'importation du fichier a échoué.",
        waitUpload: "Veuillez attendre la fin de l'importation des images.",
        cover: "COUVERTURE",
        import: "Importer",
        at: "à",
        pollsModerationTitle: "Modération des Sondages",
        manageMyPolls: "Gérer mes Sondages",
        validatePollsDesc: "Validez les sondages créés par les présidents",
        createPollsDesc: "Créez des sondages pour engager votre communauté",
        createPoll: "Créer un Sondage",
        noPollFound: "Aucun sondage trouvé",
        public: "Public",
        membersOnlyLabel: "Membres",
        multiChoice: "Multichoix",
        singleChoiceLabel: "Unique",
        participants: "participants",
        reject: "Rejeter",
        approve: "Approuver",
        newPoll: "Nouveau Sondage",
        question: "Question",
        descriptionOptional: "Description (Optionnel)",
        options: "Options",
        addOption: "Ajouter une option",
        targetAudience: "Public cible",
        allVisitors: "Tous les visiteurs",
        voteType: "Type de vote",
        singleChoiceOption: "Un seul choix",
        multiChoiceOption: "Plusieurs choix possibles",
        submit: "Soumettre",
        confirmDeletePoll: "Supprimer ce sondage définitvement ?",
        national: "National",
        bureau: "Bureau du Club",
        membre: "Membre",
        sympathisant: "Sympathisant",
        testimonialsTitle: "Avis & Témoignages",
        noTestimonials: "Aucun témoignage pour le moment.",
        confirmDeleteTestimonial: "Supprimer ce témoignage ?",
        approvedStatus: "Approuvé",
        waitingStatus: "En attente",
        pointsManagementTitle: "Gestion des Points",
        pointsManagementDesc: "Attribuez ou retirez des points bonus aux membres de votre club.",
        searchMemberPlaceholder: "Rechercher un membre par nom ou email...",
        bonusPoints: "Points Bonus",
        noMemberFound: "Aucun membre trouvé.",
        updateError: "Erreur lors de la mise à jour",
        technicalError: "Erreur technique",
        notificationsTitle: "Notifications",
        markAllAsRead: "Tout marquer comme lu",
        loadingNotifications: "Chargement des notifications...",
        errorLoading: "Erreur lors du chargement",
        serverConnectionError: "Erreur de connexion au serveur",
        retry: "Réessayer",
        noNotifications: "Vous n'avez aucune notification pour le moment.",
        markAsRead: "Marquer comme lu",
        viewDetails: "Voir les détails",
        usersManagementTitle: "Gestion des Utilisateurs",
        confirmDeleteUser: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?",
        selectAll: "Tout sélectionner",
        deselectAll: "Tout désélectionner",
        exportExcel: "Exporter en Excel",
        selectAtLeastOne: "Veuillez sélectionner au moins un utilisateur.",
        noClub: "Sans Club",
        registeredOn: "Inscrit le",
        userDetails: "Détails du membre",
        positionClub: "Position au club",
        adminNewPassword: "Nouveau mot de passe",
        leaveToKeepSame: "Laisser vide pour ne pas modifier",
        notAuthorizedRoleChange: "Vous n'êtes pas autorisé à modifier les rôles.",
        role: "Rôle",
        payment: "Paiement",
        phone: "Téléphone",
        phonePlaceholder: "N° Tel...",
        partnersManagementTitle: "Gestion des Partenaires",
        newPartner: "Nouveau Partenaire",
        confirmDeletePartner: "Supprimer ce partenaire ?",
        editPartner: "Modifier le Partenaire",
        partnerName: "Nom du Partenaire",
        websiteOptional: "Site Web (Optionnel)",
        displayOrder: "Ordre d'affichage",
        active: "Actif",
        partnerLogo: "Logo du Partenaire",
        chooseLogo: "Choisir un logo",
        visitWebsite: "Visiter le site",
        order: "Ordre",
        inactive: "Inactif",
        contentModerationTitle: "Modération des Contenus",
        addEvent: "Ajouter un événement",
        content: "Contenu",
        clubChef: "Club / Chef",
        sharing: "Partage",
        approveAction: "Approuver",
        refuseAction: "Refuser",
        home: "Accueil",
        bestOff: "Best Off",
        editContentTitle: "Modifier le Contenu",
        newContentTitle: "Nouveau Contenu",
        associateClub: "Associer au Club",
        selectClub: "Sélectionner un club",
        refused: "Refusé",
        photosSelect: "Photos (Sélectionnez une ou plusieurs)",
        importPhotos: "Importer Photos",
        videoUrlYoutube: "URL Vidéo (YouTube, Instagram, Facebook, TikTok)",
        externalLinkRegistration: "Lien externe / Inscription",
        saveChanges: "Enregistrer les modifications",
        createEvent: "Créer l'événement",
        contentSavedSuccess: "Contenu enregistré avec succès !",
        confirmDeleteContent: "Supprimer définitivement ce contenu ?",
        actionsModerationTitle: "Modération des Actions & News",
        manifestationPlan: "Plan de programme",
        addItem: "Ajouter un élément",
        globalDuration: "Durée globale",
        partsCount: "Nombre de parties",
        automaticOrdering: "Tri automatique",
        startTime: "Début",
        endTime: "Fin",
        durationMin: "Durée (min)",
        pause: "Pause",
        coffeeBreak: "Pause café",
        breakfast: "Petit déjeuner",
        lunch: "Déjeuner",
        dinner: "Dîner",
        remark: "Remarque",
        soiree: "Soirée",
        sleep: "Dormir",
        conference: "Conférence",
        formation: "Formation",
        dj_party: "DJ Party",
        spectacle: "Spectacle",
        speakerName: "Intervenant / Animateur",
        speakerPhoto: "Photo de l'intervenant",
        settingsTitle: "Paramètres de l'Association",

        // General
        loading: "Chargement...",
        error: "Erreur",
        back: "Retour",
        backToSite: "Retour au site",
        save: "Enregistrer",
        cancel: "Annuler",
        quit: "Quitter",
        edit: "Modifier",
        optional: "Optionnel",
        name: "Nom",
        create: "Créer",
        preview: "Aperçu",
        nationalBoardTitle: "Bureau National",
        newMember: "Nouveau Membre",
        confirmDeleteMember: "Supprimer ce membre du bureau ?",
        editMember: "Modifier le Membre",
        roleFunction: "Fonction / Rôle",
        rolePlaceholder: "ex: Président, Secrétaire...",
        memberPhoto: "Photo du Membre",
        choosePhoto: "Choisir une photo",
        addToBoard: "Ajouter au bureau",
        aboutManagement: "Gestion À Propos",
        aboutManagementTitle: "Gestion de la page À Propos",
        newSection: "Nouvelle Section",
        confirmDeleteSection: "Supprimer cette section ?",
        editSection: "Modifier la Section",
        objective: "Objectif",
        domain: "Domaine",
        value: "Valeur",
        icon: "Icône",
        images: "Images / Galerie",
        imageLayout: "Disposition des images",
        layoutBottom: "Bas",
        layoutTop: "Haut",
        layoutLeft: "Gauche",
        layoutRight: "Droite",
        layoutGrid: "Grille",
        layoutGrid: "Grille",
        add: "Ajouter",
        buttonText: "Texte du bouton (Optionnel)",
        buttonLink: "Lien du bouton (Optionnel)",
        buttonTextPlaceholder: "ex: Rejoindre le groupe",
        footerManagement: "Gestion du Pied de Page",
        footerManagementDesc: "Personnalisez les informations affichées dans le pied de page du site.",
        footerDescription: "Description / À propos",
        footerDescriptionPlaceholder: "Une brève description de l'association...",
        addressLocal: "Adresse / Local",
        socialLinks: "Réseaux Sociaux",
        quickLinks: "Liens Rapides",
        text: "Texte",
        ourLocations: "Nos Implantations",
        noAddress: "Adresse non renseignée",
        meetingTA: "Réunion TA",
        createMeeting: "Créer une réunion",
        scheduleMeeting: "Programmer une réunion",
        meetingDateTime: "Date et Heure",
        lateLimitMinutes: "Limite de retard (min)",
        participants: "Participants",
        meetingLink: "Lien",
        joinMeeting: "Rejoindre",
        noMeetings: "Aucune réunion prévue",
        meetingConfirmed: "Réunion créée avec succès !",
        uploadFailed: "L'importation du fichier a échoué.",
        waitUpload: "Veuillez attendre la fin de l'importation des images.",
        cover: "COUVERTURE",
        import: "Importer",
        at: "à",
        pollsModerationTitle: "Modération des Sondages",
        manageMyPolls: "Gérer mes Sondages",
        validatePollsDesc: "Validez les sondages créés par les présidents",
        createPollsDesc: "Créez des sondages pour engager votre communauté",
        createPoll: "Créer un Sondage",
        noPollFound: "Aucun sondage trouvé",
        public: "Public",
        membersOnlyLabel: "Membres",
        multiChoice: "Multichoix",
        singleChoiceLabel: "Unique",
        participants: "participants",
        reject: "Rejeter",
        approve: "Approuver",
        newPoll: "Nouveau Sondage",
        question: "Question",
        descriptionOptional: "Description (Optionnel)",
        options: "Options",
        addOption: "Ajouter une option",
        targetAudience: "Public cible",
        allVisitors: "Tous les visiteurs",
        voteType: "Type de vote",
        singleChoiceOption: "Un seul choix",
        multiChoiceOption: "Plusieurs choix possibles",
        submit: "Soumettre",
        confirmDeletePoll: "Supprimer ce sondage définitvement ?",
        national: "National",
        bureau: "Bureau du Club",
        membre: "Membre",
        sympathisant: "Sympathisant",
        testimonialsTitle: "Avis & Témoignages",
        noTestimonials: "Aucun témoignage pour le moment.",
        confirmDeleteTestimonial: "Supprimer ce témoignage ?",
        approvedStatus: "Approuvé",
        waitingStatus: "En attente",
        pointsManagementTitle: "Gestion des Points",
        pointsManagementDesc: "Attribuez ou retirez des points bonus aux membres de votre club.",
        searchMemberPlaceholder: "Rechercher un membre par nom ou email...",
        bonusPoints: "Points Bonus",
        noMemberFound: "Aucun membre trouvé.",
        updateError: "Erreur lors de la mise à jour",
        technicalError: "Erreur technique",
        notificationsTitle: "Notifications",
        markAllAsRead: "Tout marquer comme lu",
        loadingNotifications: "Chargement des notifications...",
        errorLoading: "Erreur lors du chargement",
        serverConnectionError: "Erreur de connexion au serveur",
        retry: "Réessayer",
        noNotifications: "Vous n'avez aucune notification pour le moment.",
        markAsRead: "Marquer comme lu",
        viewDetails: "Voir les détails",
        usersManagementTitle: "Gestion des Utilisateurs",
        confirmDeleteUser: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?",
        selectAll: "Tout sélectionner",
        deselectAll: "Tout désélectionner",
        exportExcel: "Exporter en Excel",
        selectAtLeastOne: "Veuillez sélectionner au moins un utilisateur.",
        noClub: "Sans Club",
        registeredOn: "Inscrit le",
        userDetails: "Détails du membre",
        positionClub: "Position au club",
        adminNewPassword: "Nouveau mot de passe",
        leaveToKeepSame: "Laisser vide pour ne pas modifier",
        notAuthorizedRoleChange: "Vous n'êtes pas autorisé à modifier les rôles.",
        role: "Rôle",
        payment: "Paiement",
        phone: "Téléphone",
        phonePlaceholder: "N° Tel...",
        partnersManagementTitle: "Gestion des Partenaires",
        newPartner: "Nouveau Partenaire",
        confirmDeletePartner: "Supprimer ce partenaire ?",
        editPartner: "Modifier le Partenaire",
        partnerName: "Nom du Partenaire",
        websiteOptional: "Site Web (Optionnel)",
        displayOrder: "Ordre d'affichage",
        active: "Actif",
        partnerLogo: "Logo du Partenaire",
        chooseLogo: "Choisir un logo",
        visitWebsite: "Visiter le site",
        order: "Ordre",
        inactive: "Inactif",
        contentModerationTitle: "Modération des Contenus",
        addEvent: "Ajouter un événement",
        content: "Contenu",
        clubChef: "Club / Chef",
        sharing: "Partage",
        approveAction: "Approuver",
        refuseAction: "Refuser",
        home: "Accueil",
        bestOff: "Best Off",
        editContentTitle: "Modifier le Contenu",
        newContentTitle: "Nouveau Contenu",
        associateClub: "Associer au Club",
        selectClub: "Sélectionner un club",
        refused: "Refusé",
        photosSelect: "Photos (Sélectionnez une ou plusieurs)",
        importPhotos: "Importer Photos",
        videoUrlYoutube: "URL Vidéo (YouTube, Instagram, Facebook, TikTok)",
        externalLinkRegistration: "Lien externe / Inscription",
        saveChanges: "Enregistrer les modifications",
        createEvent: "Créer l'événement",
        contentSavedSuccess: "Contenu enregistré avec succès !",
        confirmDeleteContent: "Supprimer définitivement ce contenu ?",
        actionsModerationTitle: "Modération des Actions & News",
        manifestationPlan: "Plan de programme",
        addItem: "Ajouter un élément",
        globalDuration: "Durée globale",
        partsCount: "Nombre de parties",
        automaticOrdering: "Tri automatique",
        startTime: "Début",
        endTime: "Fin",
        durationMin: "Durée (min)",
        pause: "Pause",
        coffeeBreak: "Pause café",
        breakfast: "Petit déjeuner",
        lunch: "Déjeuner",
        dinner: "Dîner",
        remark: "Remarque",
        soiree: "Soirée",
        sleep: "Dormir",
        conference: "Conférence",
        formation: "Formation",
        dj_party: "DJ Party",
        spectacle: "Spectacle",
        speakerName: "Intervenant / Animateur",
        speakerPhoto: "Photo de l'intervenant",
        settingsTitle: "Paramètres de l'Association",

        // General
        loading: "Chargement...",
        error: "Erreur",
        back: "Retour",
        backToSite: "Retour au site",
        save: "Enregistrer",
        cancel: "Annuler",
        quit: "Quitter",
        edit: "Modifier",
        optional: "Optionnel",
        name: "Nom",
        create: "Créer",
        preview: "Aperçu",
        nationalBoardTitle: "Bureau National",
        newMember: "Nouveau Membre",
        confirmDeleteMember: "Supprimer ce membre du bureau ?",
        editMember: "Modifier le Membre",
        roleFunction: "Fonction / Rôle",
        rolePlaceholder: "ex: Président, Secrétaire...",
        memberPhoto: "Photo du Membre",
        choosePhoto: "Choisir une photo",
        addToBoard: "Ajouter au bureau",
        aboutManagement: "Gestion À Propos",
        aboutManagementTitle: "Gestion de la page À Propos",
        newSection: "Nouvelle Section",
        confirmDeleteSection: "Supprimer cette section ?",
        editSection: "Modifier la Section",
        objective: "Objectif",
        domain: "Domaine",
        value: "Valeur",
        icon: "Icône",
        images: "Images / Galerie",
        imageLayout: "Disposition des images",
        layoutBottom: "Bas",
        layoutTop: "Haut",
        layoutLeft: "Gauche",
        layoutRight: "Droite",
        layoutGrid: "Grille",
        layoutGrid: "Grille",
        add: "Ajouter",
        buttonText: "Texte du bouton (Optionnel)",
        buttonLink: "Lien du bouton (Optionnel)",
        buttonTextPlaceholder: "ex: Rejoindre le groupe",
        footerManagement: "Gestion du Pied de Page",
        footerManagementDesc: "Personnalisez les informations affichées dans le pied de page du site.",
        footerDescription: "Description / À propos",
        footerDescriptionPlaceholder: "Une brève description de l'association...",
        addressLocal: "Adresse / Local",
        socialLinks: "Réseaux Sociaux",
        quickLinks: "Liens Rapides",
        text: "Texte",
        ourLocations: "Nos Implantations",
        noAddress: "Adresse non renseignée",
        meetingTA: "Réunion TA",
        createMeeting: "Créer une réunion",
        scheduleMeeting: "Programmer une réunion",
        meetingDateTime: "Date et Heure",
        lateLimitMinutes: "Limite de retard (min)",
        participants: "Participants",
        meetingLink: "Lien",
        joinMeeting: "Rejoindre",
        noMeetings: "Aucune réunion prévue",
        meetingConfirmed: "Réunion créée avec succès !",
        meetingNotificationTitle: "Nouvelle Réunion TA",
        meetingNotificationMessage: "Vous êtes invité à la réunion : {title}",
        meetingSettings: "Gestion Réunion TA",
        authorizedRoles: "Rôles autorisés",
        authorizedUsers: "Utilisateurs spécifiques",
        pointsAwarded: "Point de présence attribué !",
    },
    en: {
        // Club Request Modal
        errorLoadingMembers: "Failed to load members.",
        errorDuplicateRole: "The same member cannot occupy two positions on the board. Please correct your selection.",
        errorCompleteFields: "Please fill in all fields and select a member for each position.",
        errorSubmitRequest: "An error occurred while sending the request.",
        clubRequestTitle: "Club Activity Request",
        requestSubmittedSuccess: "Request submitted successfully!",
        requestSubmittedDesc: "Your request has been sent to the national board for approval. You will be notified once it is processed.",
        allMembersMustBeValid: "All board members added below must be active, valid members for this associative season.",
        activityLocation: "Location of Activity",
        clubEmailText: "Club Email",
        suggestedPassword: "Suggested Password",
        vicePresident: "Vice-President",
        secretaryGeneral: "Secretary General",
        hrManager: "HR Manager",
        eventsManager: "Events Manager",
        mediaManager: "Media Manager",
        selectMemberMenu: "-- Select a member --",
        submitRequest: "Submit Request",

        // ATA Waves
        ataWaves: "ATA Waves",
        latestEpisodes: "Latest Episodes",
        episodesCount: "episode(s)",
        noEpisodes: "No episodes available right now.",
        contentNotAvailable: "Content Not Available",
        pageNotPublished: "The ATA Waves page is not published right now.",
        video: "Video",
        by: "By",
        publishedOn: "Published on",
        unsupportedPlayer: "Player not supported for this platform",
        openVideoDirectly: "Click the button below to view the episode directly on its original platform.",
        openVideoBtn: "Open video",
        teamAta: "ATA Team",

        // Navbar
        home: "Home",
        about: "About",
        clubs: "Clubs",
        bestOff: "Best Off",
        contact: "Contact",
        games: "Games Area",
        dashboard: "Dashboard",
        connexion: "Login",
        signup: "Sign Up",
        logout: "Logout",
        installApp: "Install App",

        // Auth
        loginTitle: "Login",
        signupTitle: "Sign Up",
        welcomeBack: "Happy to see you again!",
        accountCreatedSuccess: "Your account has been created successfully. Please log in.",
        email: "Email",
        password: "Password",
        forgotPassword: "Forgot password?",
        logInProgress: "Logging in...",
        loginBtn: "Login",
        noAccountYet: "Don't have an account yet?",
        joinAta: "Join ATA",
        createAccountDesc: "Create your member account and join the adventure",
        confirmPassword: "Confirm password",
        passwordsDontMatch: "Passwords do not match.",
        signupProgress: "Creating account...",
        signupNotice: "Note: Your account must be approved by an administrator before you can access all features.",
        chooseClub: "Choose a club",
        selectFavoriteClub: "Select your favorite club",
        alreadyHaveAccount: "Already have an account?",
        loginAction: "Log In",
        signupAction: "Sign Up",
        forgotPasswordTitle: "Forgot Password",
        forgotPasswordSubtitle: "Enter your email address to receive a reset link.",
        sendResetLink: "Send Link",
        sendingLink: "Sending...",
        backToLogin: "Back to Login",
        newPasswordTitle: "New Password",
        newPasswordSubtitle: "Enter your new password below.",
        resetPasswordBtn: "Reset Password",
        resettingBtn: "Resetting...",
        invalidToken: "Invalid or missing reset token.",
        requestNewLink: "Request a new link.",
        resetSuccessRedirect: "Your password has been reset. Redirecting to login page...",
        
        // Recruitment 
        recruitmentTitle: "📢 Note: Registration Period Status",
        recruitmentDays: "There are",
        recruitmentDaysAfter: "day(s) left before registration closes.",
        recruitmentClosesAt: "(Closure planned for",
        recruitmentOpen: "The registration period for this season is currently open.",
        registrationClosedTitle: "Registrations Closed",
        registrationClosedMessage: "The registration period for this season is not currently open.",
        backToHome: "Back to Home",
        meetingTA: "TA Meeting",
        createMeeting: "Create Meeting",
        scheduleMeeting: "Schedule Meeting",
        meetingDateTime: "Date and Time",
        lateLimitMinutes: "Late limit (min)",
        participants: "Participants",
        meetingLink: "Link",
        joinMeeting: "Join",
        noMeetings: "No meetings scheduled",
        meetingConfirmed: "Meeting created successfully!",
        meetingNotificationTitle: "New TA Meeting",
        meetingNotificationMessage: "You are invited to the meeting: {title}",
        meetingSettings: "TA Meeting Management",
        authorizedRoles: "Authorized Roles",
        authorizedUsers: "Specific Users",
        pointsAwarded: "Attendance point awarded!",
        directMeeting: "Direct (immediate)",
        scheduledMeeting: "Scheduled",
        selectClubs: "Select clubs",
        selectMembers: "Select members",
        meetingDeleted: "Meeting deleted",
        confirmDeleteMeeting: "Delete this meeting?",

        // Home
        brandName: "Touches D'Art",
        heroTitle: "Express your creativity with",
        heroSubtitle: "Cultural, artistic and academic association. Join a passionate community and participate in innovative projects.",
        discoverClubs: "Discover clubs",
        joinUs: "Join Us",
        accessDashboard: "Access Dashboard",
        newsEvents: "News & Events",
        upcomingActivities: "Don't miss our clubs' upcoming events.",
        featured: "Featured",
        artCulture: "Art & Culture",
        artCultureDesc: "Workshops and events to promote art in all its forms.",
        community: "Community",
        communityDesc: "A network of students and enthusiasts united by creativity.",
        excellence: "Excellence",
        excellenceDesc: "High-level academic and artistic projects.",
        ourClubs: "Our Clubs",
        viewPage: "View Page",
        noDescription: "No description available at the moment.",
        learnMore: "Learn more",

        // Best Off
        bestOffSubtitle: "Explore the highlights and exceptional achievements of the Touches D'Art community.",
        bestOffEmpty: "The gallery is currently being prepared. Come back soon!",

        // Search
        searchPlaceholder: "Search on page...",
        results: "results",

        // Clubs
        ourClubsTitle: "Our Clubs",
        ourClubsSubtitle: "Discover the richness of our activity poles. There is bound to be a club for you.",
        noClubs: "No clubs registered yet. Check the Administration area.",
        clubATA: "ATA Club",
        backToClubs: "Back to clubs",
        aboutClub: "About the club",
        followUs: "Follow us",
        activeMembers: "Active Members",
        realTime: "Real time",
        birthdayTitle: "It's a party! 🎂",
        birthdaySubtitle: "Happy birthday to our exceptional member:",
        birthdaySubtitlePlural: "Happy birthday to our exceptional members:",
        birthdaySubtitleDesc: "Let's celebrate our exceptional members together!",
        noBirthdayToday: "No birthdays today!",
        comeBackTomorrow: "Come back tomorrow to celebrate our members.",
        itsTheirDay: "Today is their day!",
        president: "President",
        nationalBoardMember: "National Board Member",
        eventsFormations: "Events & Training",
        photoGallery: "Photo Gallery",
        videosCreations: "Videos & Creations",
        testimonialsTitle: "Reviews & Testimonials",
        leaveReview: "Leave a review",
        close: "Close",
        yourName: "Your name (Optional if member)",
        fullName: "Full name",
        rating: "Rating",
        yourMessage: "Your message",
        shareExperience: "Share your experience...",
        sendReview: "Send my review",
        reviewSuccess: "Thank you! Your review has been sent and will be visible after validation.",
        noReviews: "No reviews yet. Be the first!",
        anonymous: "Anonymous",

        // About
        aboutTitle: "Touches D'Art",
        aboutDesc: "\"Touches d'Art\" is a cultural association that welcomes a group of creative young people with varied talents, such as event organization, public animation, journalism and media, painting, singing and many other forms of art and talents.",
        objectivesTitle: "Association Objectives",
        obj1: "Contribute to anchoring the values of volunteering and the spirit of initiative in youth environments.",
        obj2: "Support domestic tourism and promote tourist sites.",
        obj3: "Promote historical monuments in Tunisia in coordination with officials.",
        domainsTitle: "Our Fields of Activity",
        domain1Title: "Cultural & Artistic Field",
        domain1Desc: "The club focuses on the cultural aspect, particularly among young people, by organizing cultural activities aimed at enriching the cultural scene and providing artistic touches.",
        domain2Title: "Social & Educational Field",
        domain2Desc: "We create coherence between the name and the theme of the association by promoting collective learning and the sharing of know-how between members.",
        domain3Title: "Recreational Field",
        domain3Desc: "Moments of relaxation for members, while opening our doors to the public through the organization of various activities and recreational outings.",
        valuesTitle: "Our Values",
        value1Title: "Excellence",
        value1Desc: "Provide high-quality academic and artistic content and events.",
        value2Title: "Passion",
        value2Desc: "Encourage everyone to fully live their interests and share them.",
        value3Title: "Innovation",
        value3Desc: "Constantly push boundaries by merging traditional art and modernity.",
        boardTitle: "National Board",
        pollsTitle: "We value your opinion",

        // Contact
        contactTitle: "Contact Us",
        contactSubtitle: "A question, a proposal or a complaint? Write to us.",
        subject: "Subject",
        selectSubject: "Select a subject",
        info: "Information request",
        partnership: "Partnership proposal",
        complaint: "Complaint",
        other: "Other",
        message: "Message",
        messagePlaceholder: "Your message...",
        yourEmail: "Your Email",
        send: "Send message",
        sending: "Sending...",
        success: "Message sent successfully! We will reply soon.",

        // Modal
        clubLabel: "Club",
        noDescAvailable: "No description available.",
        featuredPhoto: "Featured Photo",
        eventVideo: "Event Video",
        photoAlbum: "Photo Album",
        participate: "Participate / See more",

        // Polls
        resultsLabel: "Results",
        votesLabel: "votes",

        // Dashboard
        closeProfile: "Close profile",
        noActivityData: "Insufficient activity data",
        clubNews: "Club News",
        next10Days: "(Next 10 days)",
        warningTitle: "Official Warning",
        agrementTitle: "Club Accreditation and Activity",
        agrementBtn: "Make an activity request",
        agrementDesc1: "It is strictly forbidden to create or continue any club activity under the supervision of the Touches D'Art Association without submitting an official request and obtaining prior approval from the Association. The request must be created on the site. It must specify the place of activity as well as the list of club board members chosen via a dropdown list for each responsibility: President, Vice-President, Secretary General, HR Manager, Events Manager, and Communication Manager. All board members must obligatorily be ",
        agrementDesc2: "valid active members",
        agrementDesc3: " of the Association. The request must be renewed and officially approved at the beginning of each associative season. Any activity carried out without respecting these conditions is considered unauthorized and does not represent the Touches D'Art Association.",
        memberVoiceTitle: "Members Voice",
        thanksParticipation: "Thank you for your participation!",
        voteBtn: "Vote",
        votingBtn: "Sending...",
        multipleChoices: "Multiple choices allowed",
        singleChoice: "Single choice only",
        membersOnly: "Members only",
        openToAll: "Open to all",
        voteError: "An error occurred while voting",

        // Dashboard
        dashboardTitle: "Dashboard",
        dashboardOverview: "Overview",
        myProfile: "My Profile",
        notifications: "Notifications",
        messaging: "Messaging",
        memberVoice: "Member Voice",
        voiceManagement: "Member Voice Management",
        demandsReclamations: "Demands & Complaints",
        users: "Users",
        clubsManagement: "Clubs Management",
        membersManagement: "Members Management",
        nationalBoard: "National Board",
        partners: "Partners",
        contents: "Contents",
        actionsModeration: "Actions Moderation",
        pollsModeration: "Polls Moderation",
        actionsManagement: "Actions Management",
        generalSettings: "General Settings",
        myClub: "My Club",
        pageSettings: "Page Settings",
        contentsEvents: "Contents & Events",
        actionsAttendance: "Actions & Attendance",
        reviewsTestimonials: "Reviews & Testimonials",
        polls: "Polls",
        totalActions: "Total Actions",
        recentActivity: "Recent Activity",
        engagementPerformance: "Engagement & Performance",
        points: "pts",
        clubNews: "Clubs News",
        memberVoiceSubtitle: "A secure space to share your problems, concerns or remarks. Your voice matters to us.",
        yourMessageLabel: "Your message / problem description",
        messagePlaceholderVoice: "Describe here what you want to tell us...",
        submissionMode: "How would you like to submit this message?",
        anonymousMode: "Anonymous",
        identifiedMode: "Identified",
        messageSentSuccess: "Thank you for sharing",
        messageSentDesc: "Your message has been transmitted in complete confidentiality. We attach great importance to your well-being within Touches D'Art.",
        sendAnother: "Send another message",
        sendingVoice: "Sending...",
        sendMyMessage: "Send my message",
        adminNotice: "Your message will be processed by the administration and the president of your club (if applicable).",
        profileTitle: "My Profile",
        firstName: "First Name",
        lastName: "Last Name",
        phoneWhatsApp: "Phone / WhatsApp",
        birthDate: "Birth Date",
        favoriteClub: "Favorite Club",
        selectClub: "Select a club",
        profileUpdated: "Profile updated successfully!",
        membershipCard: "My Membership Card",
        security: "Security",
        serverError: "Server error.",
        loadingProfile: "Loading profile...",
        sessionExpired: "Your session has expired or is invalid. Please log in again.",
        errorLoadingProfile: "Error loading profile.",
        searchMember: "Search for a member...",
        noUserFound: "No user found",
        startConversation: "Start a conversation with",
        typeMessage: "Type your message...",
        internalMessaging: "Internal Messaging",
        selectMemberToChat: "Select a member from the list to start a discussion.",
        seen: "Seen",
        sent: "Sent",
        reclamationsTitle: "Demands & Complaints (Visitors)",
        noReclamations: "No complaints or partnership requests at the moment.",
        subjectInfo: "Info Request",
        subjectPartnership: "Partnership Proposal",
        subjectComplaint: "Complaint / Claim",
        newBadge: "NEW",
        delete: "Delete",
        receivedOn: "Received on",
        replyByEmail: "Reply by Email",
        status: "Status",
        paid: "Paid",
        notPaid: "Not Paid",
        pending: "Pending",
        approved: "Approved",
        rejected: "Rejected",
        pendingActivityRequests: "Pending Activity Requests",
        activeClubs: "Active Clubs",
        hiddenFromSite: "Hidden from site",
        clubActive: "Active Club",
        clubInactive: "Inactive Club",
        deactivate: "Deactivate",
        reactivate: "Reactivate",
        confirmReactivateClub: "Do you want to reactivate the club \"{clubName}\"? Its members not individually deactivated by the admin will be reactivated.",
        confirmDeactivateClub: "Do you want to deactivate the club \"{clubName}\"? All its members will also be deactivated.",
        confirmApproveRequest: "Accept the request for \"{clubName}\"?\n\n✅ This will:\n- Create the club page\n- Create the account with the \"club\" role\n- Award 5 score points to the club\n- Assign board positions to members",
        confirmRejectRequest: "Reject the request for \"{clubName}\"?\n\nThe club will not be created.",
        acceptAndCreate: "✅ Accept & Create",
        rejectBtn: "❌ Reject",
        processing: "⏳ Processing...",
        processingShort: "⏳ ...",
        confirmShowClub: "Show \"{clubName}\" again in the public club list?",
        confirmHideClub: "Hide \"{clubName}\" from the public club list?\n\nThe club will not be deleted, just invisible on the site.",
        proposedBureau: "Proposed Board:",
        waiting: "Waiting",
        clubsManagementTitle: "Clubs Management",
        newClub: "New Club",
        editClub: "Edit Club",
        confirmDeleteClub: "Delete this club?",
        slugLabel: "Slug (url, e.g.: theatre-club)",
        description: "Description",
        selectPresident: "Select a President",
        activeMembersLabel: "Active Members",
        partnerReviewsLabel: "Partner Reviews",
        coverImage: "Cover Image",
        chooseImage: "Choose an image",
        uploading: "Uploading...",
        update: "Update",
        createClub: "Create Club",
        manageMyPage: "Manage my page",
        identityDescription: "Identity & Description",
        clubDescription: "Club description",
        activeMembersOfMonth: "Active Members of the Month",
        selectMembersToHighlight: "Select members to highlight this month.",
        addMember: "Add a member",
        chooseMember: "Choose a member",
        roleOptional: "Role (optional)",
        period: "Period",
        noFeaturedMembers: "No featured members for now.",
        addReview: "Add a review",
        author: "Author",
        organization: "Organization",
        reviewContent: "Review content",
        saveAllChanges: "Save all changes",
        savingChanges: "Saving changes...",
        changesSaved: "Changes saved!",
        loadingMyClub: "Loading your club...",
        noClubAssigned: "No club has been assigned to you by the administrator.",
        selectMember: "-- Select --",
        newAction: "New Action",
        noActionsFound: "No actions found. Create one to start.",
        addFirstAction: "Add my first action",
        confirmDeleteAction: "Are you sure you want to delete this action?",
        manageAttendance: "Manage attendance",
        addAction: "Add an Action",
        actionTitle: "Action Title",
        startDateLabel: "Start Date",
        startTimeLabel: "Local Time",
        creating: "Creating...",
        createAction: "Create action",
        actions: "Actions",
        attendanceList: "Attendance List",
        present: "Present",
        noMemberFoundClub: "No member found for this club.",
        detailsUpdated: "Details updated!",
        attendanceUpdated: "Attendance updated successfully!",
        actionNotFound: "Action not found.",
        errorLoadingAction: "Error loading action.",
        addRemark: "Add a remark...",
        contentsEventsTitle: "Contents & Events",
        noContentPublished: "No content published yet.",
        editContent: "Edit content",
        newContent: "New Content",
        type: "Type",
        event: "Event",
        formation: "Training",
        photoGalleryLabel: "Photo / Gallery",
        videoYoutube: "Video (YouTube, Instagram, Facebook, TikTok)",
        announcement: "Announcement",
        galleryPhotos: "Photo Gallery",
        imagesImported: "image(s) imported",
        clearAll: "Clear all",
        noPhotoSelected: "No photo selected",
        videoUrl: "Video URL (YouTube, Instagram, Facebook, TikTok)",
        externalLink: "External link",
        submitForValidation: "Submit for validation",
        contentUpdated: "Content updated!",
        contentSubmitted: "Content submitted successfully!",
        uploadFailed: "File upload failed.",
        waitUpload: "Please wait for images to finish uploading.",
        cover: "COVER",
        import: "Import",
        at: "at",
        pollsModerationTitle: "Polls Moderation",
        notificationsTitle: "Notifications",
        markAllAsRead: "Mark all as read",
        loadingNotifications: "Loading notifications...",
        errorLoading: "Error loading",
        serverConnectionError: "Server connection error",
        retry: "Retry",
        noNotifications: "You have no notifications right now.",
        viewDetails: "View details",
        selectAtLeastOne: "Please select at least one user.",
        noClub: "No Club",
        phonePlaceholder: "Phone No...",
        contentModerationTitle: "Content Moderation",
        addEvent: "Add Event",
        content: "Content",
        clubChef: "Club / Chief",
        sharing: "Sharing",
        approveAction: "Approve",
        refuseAction: "Refuse",
        editContentTitle: "Edit Content",
        newContentTitle: "New Content",
        associateClub: "Associate with Club",
        refused: "Refused",
        photosSelect: "Photos (Select one or more)",
        importPhotos: "Import Photos",
        videoUrlYoutube: "Video URL (YouTube)",
        externalLinkRegistration: "External Link / Registration",
        createEvent: "Create Event",
        contentSavedSuccess: "Content saved successfully!",
        confirmDeleteContent: "Permanently delete this content?",
        actionsModerationTitle: "Actions & News Moderation",
        manifestationPlan: "Manifestation Plan",
        addItem: "Add Item",
        globalDuration: "Global Duration",
        partsCount: "Parts Count",
        automaticOrdering: "Automatic Ordering",
        durationMin: "Duration (min)",
        pause: "Pause",
        coffeeBreak: "Coffee Break",
        breakfast: "Breakfast",
        lunch: "Lunch",
        dinner: "Dinner",
        soiree: "Evening",
        sleep: "Sleep",
        conference: "Conference",
        dj_party: "DJ Party",
        spectacle: "Show",
        speakerName: "Speaker / Animator",
        speakerPhoto: "Speaker Photo",
        settingsTitle: "Association Settings",
        editMember: "Edit Member",
        roleFunction: "Function / Role",
        rolePlaceholder: "e.g.: President, Secretary...",
        memberPhoto: "Member Photo",
        choosePhoto: "Choose a photo",
        addToBoard: "Add to board",
        aboutManagement: "About Management",
        aboutManagementTitle: "About Page Management",
        newSection: "New Section",
        confirmDeleteSection: "Delete this section?",
        editSection: "Edit Section",
        objective: "Objective",
        domain: "Domain",
        value: "Value",
        icon: "Icon",
        images: "Images / Gallery",
        imageLayout: "Image Layout",
        layoutBottom: "Bottom",
        layoutTop: "Top",
        layoutLeft: "Left",
        layoutRight: "Right",
        layoutGrid: "Grid",
        buttonText: "Button Text (Optional)",
        buttonLink: "Button Link (Optional)",
        buttonTextPlaceholder: "e.g.: Join group",
        footerManagement: "Footer Management",
        footerManagementDesc: "Customize the information displayed in the site footer.",
        footerDescription: "Description / About",
        footerDescriptionPlaceholder: "A brief description of the association...",
        quickLinks: "Quick Links",
        text: "Text",
        ourLocations: "Our Locations",
        noAddress: "Address not provided",

        // Sarab Quest
        sarabQuestSubtitle: "System Initialization",
        accessCode: "Access Code",
        startMissionBtn: "Start Mission",
        syncingBtn: "Syncing...",
        adminDashboardBtn: "Admin Dashboard",
        systemLoading: "Loading System...",
        totalScore: "Total Score",
        team: "Team",
        waitingMode: "Standby Mode",
        waitingText: "The game master has not started the mission yet, please wait.",
        refreshConnection: "Refresh Connection",
        missionCompleted: "Mission Completed Successfully",
        missionCompletedDesc: "All archaeological objectives have been secured successfully.",
        finalScore: "Final Score",
        currentClue: "CURRENT CLUE",
        selectOneAnswer: "Please select at least one answer!",
        enterAnswer: "Please enter an answer!",
        scanQrBtn: "Scan QR Code",
        nfcWave: "Bring the phone close to the NFC tag",
        orEnterManually: "Or enter the answer manually",
        confirmBtn: "Confirm",
        inputAnswerPlaceholder: "Enter answer here...",
        inputChoicePlaceholder: "Choose above or type here...",
        liveRanking: "Live Team Ranking",
        youLabel: "(You)",
        stageLabel: "Stage",
        missionListTitle: "MISSION LIST",
        dockMap: "Map",
        dockClues: "Clues",
        dockRanking: "Ranking",
        dockLogout: "Exit",
        cameraUpdateAlert: "Camera will be enabled in the next update!",
        nfcSearchAlert: "Searching for NFC tag...",
        errorServer: "Server connection error.",
        completedText: "completed",
        activeText: "active",
        lockedText: "locked",
        successAccess: "✔ ACCESS GRANTED",
        errorAccess: "✖ INCORRECT CODE",
        
        // Admin Sarab Quest
        sarabQuestConsole: "Console: Sarab Quest",
        createNewMission: "Create New Mission",
        loadingData: "Loading data...",
        activeStatus: "Active",
        completedStatus: "Completed",
        draftStatus: "Draft / Waiting",
        openDashboardPanel: "Open Dashboard",
        noActiveMissions: "No active missions currently.",
        setupNewMission: "Setup New Mission",
        missionName: "Mission Name",
        defaultMapShape: "Default Map Layout",
        mapPreview: "Map Preview",
        mapOptionGeneral: "Village",
        mapOptionDesert: "Desert",
        mapOptionForet: "Forest",
        mapOptionPlage: "Coast",
        descOrInstructions: "Description or Instructions (Optional)",
        createTourBtn: "Create Tour",
        confirmDeleteStage: "Are you sure you want to delete this stage?",
        mainDashboardBtn: "Main Dashboard",
        setAsReadyBtn: "Set as Ready",
        startMissionActionBtn: "Start Mission!",
        endMissionActionBtn: "End Mission",
        statusLabel: "Status:",
        cluesAndStages: "Clues & Stages",
        editingClue: "✏️ Edit Clue",
        addNewClue: "+ Add New Clue",
        clueTextPlaceholder: "Clue text (visible to participants)",
        textBtn: "✍️ Text",
        choiceBtn: "🔘 Choices",
        qrBtn: "📷 QR Code",
        nfcBtn: "📱 NFC Tag",
        stagePointsLevel: "Stage Points:",
        pointsPlaceholder: "Points",
        choiceCountLabel: "Number of Choices:",
        selectCorrectAnswerInfo: "Select the correct answer by clicking the adjacent box",
        choicePlaceholder: "Choice",
        correctAnswerSecret: "Secret correct answer (Text or Number)",
        saveEditsBtn: "Save Edits",
        addStageBtn: "+ Add Stage",
        writtenAnswer: "Written Answer",
        qcmChoices: "MCQ Choices",
        scanQr: "Scan QR",
        scanNfc: "Scan NFC",
        clueNumberPrefix: "Clue #",
        pointsSuffix: "Points",
        answerLabel: "Answer:",
        encryptedText: "[ENCRYPTED]",
        choicesLabel: "Choices:",
        downloadQrBtn: "Download QR Code to Print",
        copyNfcLinkBtn: "Copy NFC Link for Tag",
        synchronized: "Synchronized",
        competingTeams: "Competing Teams",
        newTeamPlaceholder: "New Team Name",
        addTeamBtn: "+ Add Team",
        teamCol: "Team",
        accessCodeCol: "Access Code",
        stageCol: "Stage",
        pointsCol: "Points",
        nfcCopySuccessTitle: "Link copied successfully! 📋\n\nNow head to any NFC tag writing app (like NFC Tools) and use the Write (URL / Link) option and paste it there.",
        startTime: "Start Time",
        deleteConfirmAdmin: "Delete?"
    },
    ar: {
        // Club Request Modal
        errorLoadingMembers: "تعذر تحميل الأعضاء.",
        errorDuplicateRole: "لا يمكن لنفس العضو شغل منصبين في الهيئة. يرجى تصحيح اختيارك.",
        errorCompleteFields: "يرجى ملء جميع الحقول واختيار عضو لكل منصب.",
        errorSubmitRequest: "حدث خطأ أثناء إرسال الطلب.",
        clubRequestTitle: "طلب نشاط نادي",
        requestSubmittedSuccess: "تم إرسال الطلب بنجاح!",
        requestSubmittedDesc: "تم إرسال طلبك إلى المكتب الوطني للموافقة عليه. سيتم إشعارك بمجرد معالجته.",
        allMembersMustBeValid: "يجب أن يكون جميع أعضاء الهيئة المضافين أدناه أعضاء نشطين وصالحين لهذا الموسم الجمعياتي.",
        activityLocation: "مكان النشاط",
        clubEmailText: "البريد الإلكتروني للنادي",
        suggestedPassword: "كلمة المرور المقترحة",
        vicePresident: "نائب الرئيس",
        secretaryGeneral: "الكاتب العام",
        hrManager: "مسؤول الموارد البشرية",
        eventsManager: "مسؤول الفعاليات",
        mediaManager: "مسؤول الإعلام",
        selectMemberMenu: "-- الرجاء اختيار عضو --",
        submitRequest: "تقديم الطلب",

        // Navbar
        home: "الرئيسية",
        about: "من نحن",
        clubs: "النوادي",
        bestOff: "الأفضل",
        contact: "اتصل بنا",
        dashboard: "لوحة القيادة",
        connexion: "تسجيل الدخول",
        signup: "إنشاء حساب",
        logout: "تسجيل الخروج",
        installApp: "تثبيت التطبيق",

        // Auth
        loginTitle: "تسجيل الدخول",
        signupTitle: "إنشاء حساب",
        welcomeBack: "سعيد برؤيتك مرة أخرى!",
        accountCreatedSuccess: "تم إنشاء حسابك بنجاح. يرجى تسجيل الدخول.",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        forgotPassword: "هل نسيت كلمة المرور؟",
        logInProgress: "جاري تسجيل الدخول...",
        loginBtn: "تسجيل الدخول",
        noAccountYet: "ليس لديك حساب بعد؟",
        joinAta: "انضم إلى ATA",
        createAccountDesc: "أنشئ حسابك كعضو وشارك في المغامرة",
        confirmPassword: "تأكيد كلمة المرور",
        passwordsDontMatch: "كلمات المرور غير متطابقة.",
        signupProgress: "جاري إنشاء الحساب...",
        signupNotice: "ملاحظة: يجب الموافقة على حسابك من قبل المسؤول قبل أن تتمكن من الوصول إلى جميع الميزات.",
        chooseClub: "اختر نادياً",
        selectFavoriteClub: "اختر ناديك المفضل",
        alreadyHaveAccount: "لديك حساب بالفعل؟",
        loginAction: "تسجيل الدخول",
        signupAction: "إنشاء حساب",
        forgotPasswordTitle: "نسيت كلمة المرور",
        forgotPasswordSubtitle: "أدخل بريدك الإلكتروني لتلقي رابط إعادة التعيين.",
        sendResetLink: "إرسال الرابط",
        sendingLink: "جاري الإرسال...",
        backToLogin: "العودة لتسجيل الدخول",
        newPasswordTitle: "كلمة مرور جديدة",
        newPasswordSubtitle: "أدخل كلمة المرور الجديدة أدناه.",
        resetPasswordBtn: "إعادة تعيين كلمة المرور",
        resettingBtn: "جاري إعادة التعيين...",
        invalidToken: "رابط إعادة التعيين غير صالح أو مفقود.",
        requestNewLink: "طلب رابط جديد.",
        resetSuccessRedirect: "تمت إعادة تعيين كلمة المرور بنجاح. جاري توجيهك لصفحة تسجيل الدخول...",
        
        // Recruitment
        recruitmentTitle: "📢 ملاحظة: حالة فترة التسجيل",
        recruitmentDays: "يتبقى",
        recruitmentDaysAfter: "يوم (أيام) قبل إغلاق التسجيل.",
        recruitmentClosesAt: "(الإغلاق المقرر في",
        recruitmentOpen: "فترة التسجيل لهذا الموسم مفتوحة حاليا.",
        registrationClosedTitle: "التسجيل مغلق",
        registrationClosedMessage: "فترة التسجيل لهذا الموسم غير مفتوحة حاليا.",
        backToHome: "العودة للرئيسية",

        ataWaves: "أمواج أطا",
        latestEpisodes: "أحدث الحلقات",
        episodesCount: "حلقة/حلقات",
        noEpisodes: "لا توجد حلقات متاحة في الوقت الحالي.",
        contentNotAvailable: "المحتوى غير متوفر",
        pageNotPublished: "صفحة ATA Waves غير منشورة حالياً.",
        video: "فيديو",
        by: "بواسطة",
        publishedOn: "نُشر في",
        unsupportedPlayer: "المشغل غير مدعوم على هذه المنصة",
        openVideoDirectly: "انقر على الزر أدناه لمشاهدة الحلقة مباشرة على المنصة الأصلية.",
        openVideoBtn: "فتح الفيديو",
        teamAta: "فريق أطا",

        // Home
        brandName: "لمسات فنّية",
        heroTitle: "عبر عن إبداعك مع",
        heroSubtitle: "جمعية ثقافية وفنية وأكاديمية. انضم إلى مجتمع شغوف وشارك في مشاريع مبتكرة.",
        discoverClubs: "اكتشف النوادي",
        joinUs: "انضم إلينا",
        accessDashboard: "دخول لوحة القيادة",
        games: "فضاء الألعاب",
        newsEvents: "الأخبار والفعاليات",
        upcomingActivities: "فعاليات نوادينا التي لا يجب تفويتها.",
        featured: "في الواجهة",
        artCulture: "الفن والثقافة",
        artCultureDesc: "ورش عمل وفعاليات لتعزيز الفن بجميع أشكاله.",
        community: "المجتمع",
        communityDesc: "شبكة من الطلاب والشغوفين يجمعهم الإبداع.",
        excellence: "التميز",
        excellenceDesc: "مشاريع أكاديمية وفنية رفيعة المستوى.",
        ourClubs: "نوادينا",
        viewPage: "عرض الصفحة",
        noDescription: "لا يوجد وصف متاح حالياً.",
        learnMore: "اقرأ المزيد",

        // Best Off
        bestOffSubtitle: "استكشف أبرز اللحظات والإنجازات الاستثنائية لمجتمع لمسات فنّية.",
        bestOffEmpty: "المعرض قيد التحضير. عد قريباً!",

        // Search
        searchPlaceholder: "بحث في الصفحة...",
        results: "نتائج",

        // Clubs
        ourClubsTitle: "نوادينا",
        ourClubsSubtitle: "اكتشف ثراء أقطاب نشاطنا. بالتأكيد هناك نادٍ مناسب لك.",
        noClubs: "لم يتم تسجيل أي نوادي بعد. راجع منطقة الإدارة.",
        clubATA: "نادي ATA",
        backToClubs: "العودة إلى النوادي",
        aboutClub: "حول النادي",
        followUs: "تابعنا",
        activeMembers: "الأعضاء النشطون",
        realTime: "الوقت الفعلي",
        birthdayTitle: "إنه وقت الاحتفال! 🎂",
        birthdaySubtitle: "عيد ميلاد سعيد لعضونا المتميز:",
        birthdaySubtitlePlural: "عيد ميلاد سعيد لأعضائنا المتميزين:",
        birthdaySubtitleDesc: "دعونا نحتفل معاً بأعضائنا المتميزين!",
        noBirthdayToday: "لا توجد أعياد ميلاد اليوم!",
        comeBackTomorrow: "عد غداً للاحتفال بأعضائنا.",
        itsTheirDay: "اليوم هو يومهم المميز!",
        president: "الرئيس",
        nationalBoardMember: "عضو مكتب وطني",
        eventsFormations: "الفعاليات والتكوينات",
        photoGallery: "معرض الصور",
        videosCreations: "الفيديوهات والإنجازات",
        testimonialsTitle: "الآراء والشهادات",
        leaveReview: "اترك رأياً",
        close: "إغلاق",
        yourName: "اسمك (اختياري إذا كنت عضواً)",
        fullName: "الاسم الكامل",
        rating: "التقييم",
        yourMessage: "رسالتك",
        shareExperience: "شارك تجربتك...",
        sendReview: "إرسال رأيي",
        reviewSuccess: "شكراً لك! تم إرسال رأيك وسيظهر بعد التحقق منه.",
        noReviews: "لا توجد آراء حالياً. كن أول من يعلق!",
        anonymous: "مجهول",

        // About
        aboutTitle: "لمسات فنّية",
        aboutDesc: "\"لمسات فنّية\" هي جمعية ثقافية تستقبل مجموعة من الشباب المبدعين ذوي المواهب المتنوعة، مثل تنظيم الفعاليات، وتنشيط الجمهور، والصحافة والإعلام، والرسم، والغناء والعديد من أشكال الفن والمواهب الأخرى.",
        objectivesTitle: "أهداف الجمعية",
        obj1: "المساهمة في ترسيخ قيم التطوع وروح المبادرة في أوساط الشباب.",
        obj2: "دعم السياحة الداخلية والترويج للمواقع السياحية.",
        obj3: "الترويج للمعالم التاريخية في تونس بالتنسيق مع المسؤولين.",
        domainsTitle: "مجالات نشاطنا",
        domain1Title: "المجال الثقافي والفني",
        domain1Desc: "يركز النادي على الجانب الثقافي، خاصة لدى الشباب، من خلال تنظيم أنشطة ثقافية تهدف إلى إثراء المشهد الثقافي وتقديم لمسات فنية.",
        domain2Title: "المجال الاجتماعي والتربوي",
        domain2Desc: "نخلق انسجاماً بين اسم الجمعية وموضوعها من خلال تعزيز التعلم الجماعي وتبادل الخبرات بين الأعضاء.",
        domain3Title: "المجال الترفيهي",
        domain3Desc: "لحظات من الاسترخاء للأعضاء، مع فتح أبوابنا للجمهور من خلال تنظيم أنشطة متنوعة ورحلات ترفيهية.",
        valuesTitle: "قيمنا",
        value1Title: "التميز",
        value1Desc: "تقديم محتويات وفعاليات ذات جودة أكاديمية وفنية عالية.",
        value2Title: "الشغف",
        value2Desc: "تشجيع الجميع على عيش اهتماماتهم بالكامل ومشاركتها.",
        value3Title: "الابتكار",
        value3Desc: "دفع الحدود باستمرار من خلال دمج الفن التقليدي والحداثة.",
        boardTitle: "المكتب الوطني",
        pollsTitle: "رأيكم يهمنا",

        // Contact
        contactTitle: "اتصل بنا",
        contactSubtitle: "سؤال، اقتراح أو شكوى? اكتب لنا.",
        subject: "الموضوع",
        selectSubject: "اختر موضوعاً",
        info: "طلب معلومات",
        partnership: "اقتراح شراكة",
        complaint: "شكوى",
        other: "آخر",
        message: "الرسالة",
        messagePlaceholder: "رسالتك...",
        yourEmail: "بريدك الإلكتروني",
        send: "إرسال الرسالة",
        sending: "جاري الإرسال...",
        success: "تم إرسال الرسالة بنجاح! سنرد عليك قريباً.",

        // Modal
        clubLabel: "النادي",
        noDescAvailable: "لا يوجد وصف متاح.",
        featuredPhoto: "الصورة المميزة",
        eventVideo: "فيديو الفعالية",
        photoAlbum: "ألبوم الصور",
        participate: "المشاركة / عرض المزيد",

        // Polls
        resultsLabel: "النتائج",
        votesLabel: "أصوات",
        thanksParticipation: "شكراً لمشاركتك!",
        voteBtn: "تصويت",
        votingBtn: "جاري الإرسال...",
        multipleChoices: "يسمح بخيارات متعددة",
        singleChoice: "خيار واحد فقط",
        membersOnly: "للأعضاء فقط",
        openToAll: "مفتوح للجميع",
        voteError: "حدث خطأ أثناء التصويت",

        // Dashboard
        dashboardTitle: "لوحة القيادة",
        dashboardOverview: "نظرة عامة",
        myProfile: "ملفي الشخصي",
        notifications: "الإشعارات",
        messaging: "المراسلة",
        memberVoice: "صوت الأعضاء",
        voiceManagement: "إدارة صوت الأعضاء",
        demandsReclamations: "الطلبات والشكاوى",
        users: "المستخدمين",
        clubsManagement: "إدارة النوادي",
        membersManagement: "إدارة الأعضاء",
        nationalBoard: "المكتب الوطني",
        partners: "الشركاء",
        contents: "المحتويات",
        actionsModeration: "مراجعة الأنشطة",
        pollsModeration: "مراجعة الاستطلاعات",
        actionsManagement: "إدارة الأنشطة",
        generalSettings: "الإعدادات العامة",
        myClub: "ناديي",
        pageSettings: "إعدادات الصفحة",
        contentsEvents: "المحتويات والفعاليات",
        actionsAttendance: "الأنشطة والحضور",
        reviewsTestimonials: "الآراء والشهادات",
        polls: "الاستطلاعات",
        totalActions: "إجمالي الأنشطة",
        recentActivity: "النشاط الأخير",
        engagementPerformance: "التفاعل والأداء",
        points: "نقطة",
        closeProfile: "إغلاق الملف الشخصي",
        noActivityData: "بيانات النشاط غير كافية",
        clubNews: "أخبار النوادي",
        next10Days: "(الـ 10 أيام القادمة)",
        warningTitle: "تحذير رسمي",
        agrementTitle: "اعتماد ونشاط الأندية",
        agrementBtn: "تقديم طلب نشاط",
        agrementDesc1: "يُمنع منعًا باتًا إنشاء أو مواصلة أي نشاط لأي نادي تحت إشراف جمعية لمسات فنية دون تقديم طلب رسمي والحصول على موافقة مسبقة من الجمعية. يجب إنشاء الطلب على الموقع. ويجب أن يُحدد مكان النشاط بالإضافة إلى قائمة أعضاء هيئة النادي المختارين عبر قائمة منسدلة لكل مسؤولية: الرئيس، نائب الرئيس، الكاتب العام، مسؤول الموارد البشرية، مسؤول الفعاليات ومسؤول الإعلام. يجب أن يكون جميع أعضاء الهيئة بالضرورة ",
        agrementDesc2: "أعضاء نشطين وصالحين",
        agrementDesc3: " في الجمعية. يجب تجديد الطلب واعتماده رسميًا في بداية كل موسم جمعياتي. أي نشاط يُمارس دون احترام هذه الشروط يُعتبر غير مصرح به ولا يمثل جمعية لمسات فنية.",
        memberVoiceTitle: "صوت الأعضاء",
        memberVoiceSubtitle: "مساحة آمنة لمشاركة مشاكلك أو مخاوفك أو ملاحظاتك. صوتك يهمنا.",
        yourMessageLabel: "رسالتك / وصف المشكلة",
        messagePlaceholderVoice: "صف هنا ما تريد إخبارنا به...",
        submissionMode: "كيف ترغب في إرسال هذه الرسالة؟",
        anonymousMode: "مجهول",
        identifiedMode: "محدد الهوية",
        messageSentSuccess: "شكراً لمشاركتك",
        messageSentDesc: "تم إرسال رسالتك بكل سرية. نحن نولي أهمية كبيرة لرفاهيتك داخل لمسات فنّية.",
        sendAnother: "إرسال رسالة أخرى",
        sendingVoice: "جاري الإرسال...",
        sendMyMessage: "إرسال رسالتي",
        adminNotice: "سيتم معالجة رسالتك من قبل الإدارة ورئيس ناديك (إن وجد).",
        profileTitle: "ملفي الشخصي",
        firstName: "الاسم الأول",
        lastName: "اللقب",
        phoneWhatsApp: "الهاتف / واتساب",
        birthDate: "تاريخ الميلاد",
        favoriteClub: "النادي المفضل",
        selectClub: "اختر نادياً",
        saveChanges: "حفظ التغييرات",
        profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
        membershipCard: "بطاقة العضوية",
        security: "الأمان",
        newPassword: "كلمة سر جديدة",
        confirmPassword: "تأكيد كلمة السر",
        updateError: "حدث خطأ أثناء التحديث.",
        serverError: "خطأ في الخادم.",
        loadingProfile: "جاري تحميل الملف الشخصي...",
        searchMember: "البحث عن عضو...",
        noUserFound: "لم يتم العثور على مستخدم",
        startConversation: "ابدأ محادثة مع",
        typeMessage: "اكتب رسالتك...",
        internalMessaging: "المراسلة الداخلية",
        selectMemberToChat: "اختر عضواً من القائمة لبدء المحادثة.",
        seen: "تمت المشاهدة",
        sent: "تم الإرسال",
        reclamationsTitle: "الطلبات والشكاوى (الزوار)",
        noReclamations: "لا توجد شكاوى أو طلبات شراكة حالياً.",
        subjectInfo: "طلب معلومات",
        subjectPartnership: "اقتراح شراكة",
        subjectComplaint: "شكوى / تظلم",
        newBadge: "جديد",
        markAsRead: "تحديد كمقروء",
        delete: "حذف",
        receivedOn: "تم الاستلام في",
        replyByEmail: "الرد عبر البريد الإلكتروني",
        usersManagementTitle: "إدارة المستخدمين",
        selectAll: "تحديد الكل",
        deselectAll: "إلغاء تحديد الكل",
        exportExcel: "تصدير Excel",
        registeredOn: "عضو منذ",
        userDetails: "تفاصيل العضو",
        positionClub: "المنصب في النادي",
        adminNewPassword: "كلمة سر جديدة",
        leaveToKeepSame: "اتركه فارغاً للاحتفاظ بالحالية",
        notAuthorizedRoleChange: "ليس لديك صلاحية لتغيير الأدوار.",
        member: "عضو",
        role: "الدور",
        payment: "الدفع",
        phone: "الهاتف",
        status: "الحالة",
        paid: "تم الدفع",
        notPaid: "لم يتم الدفع",
        pending: "قيد الانتظار",
        approved: "مقبول",
        rejected: "مرفوض",
        confirmDeleteUser: "هل تريد حذف هذا المستخدم؟",
        partnersManagementTitle: "إدارة الشركاء",
        newPartner: "شريك جديد",
        confirmDeletePartner: "حذف هذا الشريك؟",
        editPartner: "تعديل الشريك",
        partnerName: "اسم الشريك",
        websiteOptional: "الموقع الإلكتروني (اختياري)",
        displayOrder: "ترتيب العرض",
        active: "نشط",
        partnerLogo: "شعار الشريك",
        chooseLogo: "اختر شعاراً",
        visitWebsite: "زيارة الموقع",
        order: "الترتيب",
        inactive: "غير نشط",
        pendingActivityRequests: "طلبات النشاط المعلقة",
        activeClubs: "الأندية النشطة",
        hiddenFromSite: "مخفي من الموقع",
        clubActive: "نادي نشط",
        clubInactive: "نادي غير نشط",
        deactivate: "تعطيل",
        reactivate: "تفعيل",
        confirmReactivateClub: "هل تريد إعادة تفعيل النادي \"{clubName}\"؟ سيتم إعادة تفعيل أعضائه الذين لم يتم تعطيلهم فرديًا من قبل المسؤول.",
        confirmDeactivateClub: "هل تريد تعطيل النادي \"{clubName}\"؟ سيتم تعطيل جميع أعضائه أيضًا.",
        confirmApproveRequest: "قبول الطلب لـ \"{clubName}\"؟\n\n✅ سيؤدي هذا إلى:\n- إنشاء صفحة النادي\n- إنشاء الحساب بدور \"النادي\"\n- منح 5 نقاط للنادي\n- تعيين مناصب المكتب للأعضاء",
        confirmRejectRequest: "رفض الطلب لـ \"{clubName}\"؟\n\nلن يتم إنشاء النادي.",
        acceptAndCreate: "✅ قبول وإنشاء",
        rejectBtn: "❌ رفض",
        processing: "⏳ جاري المعالجة...",
        processingShort: "⏳ ...",
        confirmShowClub: "إعادة إظهار \"{clubName}\" في القائمة العامة للأندية؟",
        confirmHideClub: "إخفاء \"{clubName}\" من القائمة العامة للأندية؟\n\nلن يتم حذف النادي، بل سيكون غير مرئي على الموقع فقط.",
        proposedBureau: "المكتب المقترح:",
        waiting: "قيد الانتظار",
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('fr');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
        const savedLang = localStorage.getItem('language');
        if (savedLang && ['fr', 'en', 'ar'].includes(savedLang)) {
            setLanguage(savedLang);
        }
    }, []);

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    useEffect(() => {
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    // Helper to translate dynamic strings containing "Touches D'Art" or "Club"
    const formatDynamicText = (text) => {
        if (!text) return "";
        if (language !== 'ar') return text;

        let formatted = text;
        // Replace "Touches D'Art" (case insensitive, handling various quotes)
        formatted = formatted.replace(/Touches D'Art/gi, "لمسات فنّية");
        formatted = formatted.replace(/Touches d'Art/gi, "لمسات فنّية");
        // Replace "Club" (case insensitive)
        formatted = formatted.replace(/Club/gi, "نادي");

        return formatted;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t, formatDynamicText }}>
            <div style={{ visibility: mounted ? 'visible' : 'hidden' }}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
