"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export const LanguageContext = createContext();

export const translations = {
    fr: {
        // ATA Waves
        ataWaves: "ATA Waves",
        latestEpisodes: "Dernières Émissions",
        episodesCount: "émission(s)",
        noEpisodes: "Aucune émission disponible pour le moment.",
        contentNotAvailable: "Contenu Non Disponible",
        pageNotPublished: "La page ATA Waves n'est pas publiée en ce moment.",
        video: "Vidéo",
        by: "Par",
        publishedOn: "Publié le",
        unsupportedPlayer: "Lecteur non supporté pour cette plateforme",
        openVideoDirectly: "Cliquez sur le bouton ci-dessous pour visionner l'émission directement sur la plateforme d'origine.",
        openVideoBtn: "Ouvrir la vidéo",
        teamAta: "Équipe ATA",

        // Navbar
        home: "Accueil",
        about: "À propos",
        clubs: "Clubs",
        bestOff: "Best Off",
        contact: "Contact",
        dashboard: "Tableau de Bord",
        connexion: "Connexion",
        signup: "S'inscrire",
        logout: "Se déconnecter",
        installApp: "Installer l'App",

        // Auth
        loginTitle: "Connexion",
        signupTitle: "S'inscrire",
        welcomeBack: "Heureux de vous revoir !",
        accountCreatedSuccess: "Votre compte a été créé avec succès. Veuillez vous connecter.",
        email: "Email",
        password: "Mot de passe",
        forgotPassword: "Mot de passe oublié ?",
        logInProgress: "Connexion...",
        loginBtn: "Se connecter",
        noAccountYet: "Pas encore de compte ?",
        joinAta: "Rejoignez ATA",
        createAccountDesc: "Créez votre compte membre et participez à l'aventure",
        confirmPassword: "Confirmer mot de passe",
        passwordsDontMatch: "Les mots de passe ne correspondent pas.",
        signupProgress: "Création en cours...",
        signupNotice: "Note: Votre compte devra être approuvé par un administrateur avant de pouvoir accéder à toutes les fonctionnalités.",
        chooseClub: "Choisir un club",
        selectFavoriteClub: "Sélectionnez votre club favori",
        alreadyHaveAccount: "Déjà un compte ?",
        loginAction: "Se connecter",
        signupAction: "S'inscrire",
        forgotPasswordTitle: "Mot de passe oublié",
        forgotPasswordSubtitle: "Entrez votre adresse email pour recevoir un lien de réinitialisation.",
        sendResetLink: "Envoyer le lien",
        sendingLink: "Envoi en cours...",
        backToLogin: "Retour à la connexion",
        newPasswordTitle: "Nouveau mot de passe",
        newPasswordSubtitle: "Entrez votre nouveau mot de passe ci-dessous.",
        resetPasswordBtn: "Réinitialiser le mot de passe",
        resettingBtn: "Réinitialisation...",
        invalidToken: "Jeton de réinitialisation invalide ou manquant.",
        requestNewLink: "Demander un nouveau lien.",
        resetSuccessRedirect: "Votre mot de passe a été réinitialisé. Redirection vers la page de connexion...",

        // Home
        brandName: "Touches D'Art",
        heroTitle: "Exprimez votre créativité avec",
        heroSubtitle: "Association culturelle, artistique et académique. Rejoignez une communauté passionnée et participez à des projets innovants.",
        discoverClubs: "Découvrir les clubs",
        joinUs: "Rejoindre",
        accessDashboard: "Accéder au Dashboard",
        newsEvents: "Actualités & Événements",
        upcomingActivities: "Les événements de nos clubs à ne pas manquer.",
        featured: "À la une",
        artCulture: "Art & Culture",
        artCultureDesc: "Des ateliers et événements pour promouvoir l'art sous toutes ses formes.",
        community: "Communauté",
        communityDesc: "Un réseau d'étudiants et de passionnés unis par la créativité.",
        excellence: "Excellence",
        excellenceDesc: "Des projets académiques et artistiques de haut niveau.",
        ourClubs: "Nos Clubs",
        viewPage: "Voir la page",
        noDescription: "Aucune description disponible pour le moment.",
        learnMore: "En savoir plus",

        // Best Off
        bestOffSubtitle: "Explorez les moments marquants et les réalisations exceptionnelles de la communauté Touches D'Art.",
        bestOffEmpty: "La galerie est en cours de préparation. Revenez bientôt !",

        // Search
        searchPlaceholder: "Rechercher sur la page...",
        results: "résultats",

        // Clubs
        ourClubsTitle: "Nos Clubs",
        ourClubsSubtitle: "Découvrez la richesse de nos pôles d'activité. Il y a forcément un club fait pour vous.",
        noClubs: "Aucun club n'est encore enregistré. Revoyez l'espace Administration.",
        clubATA: "Club ATA",
        backToClubs: "Retour aux clubs",
        aboutClub: "À propos du club",
        followUs: "Suivez-nous",
        activeMembers: "Membres Actifs",
        realTime: "Temps réel",
        birthdayTitle: "C'est la fête ! 🎂",
        birthdaySubtitle: "Joyeux anniversaire à notre membre exceptionnel :",
        birthdaySubtitlePlural: "Joyeux anniversaire à nos membres exceptionnels :",
        birthdaySubtitleDesc: "Célébrons ensemble nos membres exceptionnels !",
        noBirthdayToday: "Aucun anniversaire aujourd'hui !",
        comeBackTomorrow: "Revenez demain pour célébrer nos membres.",
        itsTheirDay: "Aujourd'hui, c'est son jour !",
        president: "Président",
        nationalBoardMember: "Membre Bureau National",
        eventsFormations: "Événements & Formations",
        photoGallery: "Galerie Photos",
        videosCreations: "Vidéos & Réalisations",
        testimonialsTitle: "Avis & Témoignages",
        leaveReview: "Laisser un avis",
        close: "Fermer",
        yourName: "Votre nom (Optionnel si membre)",
        fullName: "Nom complet",
        rating: "Note",
        yourMessage: "Votre message",
        shareExperience: "Partagez votre expérience...",
        sendReview: "Envoyer mon avis",
        reviewSuccess: "Merci ! Votre avis a été envoyé et sera visible après validation.",
        noReviews: "Aucun avis pour le moment. Soyez le premier !",
        anonymous: "Anonyme",

        // About
        aboutTitle: "Touches D'Art",
        aboutDesc: "\"Touches d'Art\" est une association culturelle qui accueille un groupe de jeunes créatifs dotés de talents variés, tels que l'organisation d'événements, l'animation de publics, le journalisme et les médias, la peinture, le chant et bien d'autres formes d'art et de talents.",
        objectivesTitle: "Objectifs de l'Association",
        obj1: "Contribuer à ancrer les valeurs du bénévolat et de l'esprit d'initiative dans les milieux jeunes.",
        obj2: "Soutenir le tourisme intérieur et promouvoir les sites touristiques.",
        obj3: "Promouvoir les monuments historiques en Tunisie en coordination avec les responsables.",
        domainsTitle: "Nos Domaines d'Activité",
        domain1Title: "Domaine Culturel & Artistique",
        domain1Desc: "Le club se concentre sur l'aspect culturel, particulièrement chez les jeunes, en organisant des activités culturelles visant à enrichir la scène culturelle et à apporter des touches artistiques.",
        domain2Title: "Domaine Social & Éducatif",
        domain2Desc: "Nous créons une cohérence entre le nom et le thème de l'association en favorisant l'apprentissage collectif et le partage de savoir-faire entre les membres.",
        domain3Title: "Domaine Récréatif",
        domain3Desc: "Des moments de détente pour les membres, tout en ouvrant nos portes au public à travers l'organisation d'activités diverses et de sorties récréatives.",
        valuesTitle: "Nos Valeurs",
        value1Title: "Excellence",
        value1Desc: "Proposer des contenus et événements de haute qualité académique et artistique.",
        value2Title: "Passion",
        value2Desc: "Encourager chacun à vivre pleinement ses centres d'intérêt et à les partager.",
        value3Title: "Innovation",
        value3Desc: "Constamment repousser les limites en fusionnant art traditionnel et modernité.",
        boardTitle: "Bureau National",
        pollsTitle: "Votre avis nous intéresse",

        // Contact
        contactTitle: "Contactez-nous",
        contactSubtitle: "Une question, une proposition ou une réclamation ? Écrivez-nous.",
        subject: "Sujet",
        selectSubject: "Sélectionnez un sujet",
        info: "Demande d'information",
        partnership: "Proposition de partenariat",
        complaint: "Réclamation",
        other: "Autre",
        message: "Message",
        messagePlaceholder: "Votre message...",
        yourEmail: "Votre Email",
        send: "Envoyer le message",
        sending: "Envoi...",
        success: "Message envoyé avec succès ! Nous vous répondrons bientôt.",

        // Modal
        clubLabel: "Club",
        noDescAvailable: "Pas de description disponible.",
        featuredPhoto: "Photo à la Une",
        eventVideo: "Vidéo de l'événement",
        photoAlbum: "Album Photo",
        participate: "Participer / Voir plus",

        // Polls
        resultsLabel: "Résultats",
        votesLabel: "voix",
        thanksParticipation: "Merci pour votre participation !",
        voteBtn: "Voter",
        votingBtn: "Envoi...",
        multipleChoices: "Plusieurs choix autorisés",
        singleChoice: "Un seul choix possible",
        membersOnly: "Membres uniquement",
        openToAll: "Ouvert à tous",
        voteError: "Une erreur est survenue lors du vote",

        // Dashboard
        dashboardTitle: "Tableau de Bord",
        dashboardOverview: "Vue d'ensemble",
        myProfile: "Mon Profil",
        notifications: "Notifications",
        messaging: "Messagerie",
        memberVoice: "Voix des Membres",
        voiceManagement: "Gestion Voix Membres",
        demandsReclamations: "Demandes & Réclamations",
        users: "Utilisateurs",
        clubsManagement: "Gestion Clubs",
        membersManagement: "Gestion Membres",
        nationalBoard: "Bureau National",
        partners: "Partenaires",
        contents: "Contenus",
        actionsModeration: "Modération Actions",
        pollsModeration: "Modération Sondages",
        actionsManagement: "Gestion Actions",
        generalSettings: "Paramètres Généraux",
        myClub: "Mon Club",
        pageSettings: "Paramètres Page",
        contentsEvents: "Contenus & Événements",
        actionsAttendance: "Actions & Présences",
        reviewsTestimonials: "Avis & Témoignages",
        polls: "Sondages",
        totalActions: "Actions Totales",
        recentActivity: "Activité Récente",
        engagementPerformance: "Engagement & Performance",
        points: "pts",
        closeProfile: "Fermer le profil",
        noActivityData: "Données d'activité insuffisantes",
        clubNews: "Actualités des Clubs",
        next10Days: "(Prochains 10 jours)",
        memberVoiceTitle: "Voix des Membres",
        memberVoiceSubtitle: "Un espace sécurisé pour partager vos problèmes, préoccupations ou remarques. Votre voix compte pour nous.",
        yourMessageLabel: "Votre message / description du problème",
        messagePlaceholderVoice: "Décrivez ici ce que vous souhaitez nous dire...",
        submissionMode: "Comment souhaitez-vous soumettre ce message ?",
        anonymousMode: "Anonyme",
        identifiedMode: "Identifié",
        messageSentSuccess: "Merci pour votre partage",
        messageSentDesc: "Votre message a été transmis en toute confidentialité. Nous accordons une grande importance à votre bien-être au sein de Touches D'Art.",
        sendAnother: "Envoyer un autre message",
        sendingVoice: "Envoi en cours...",
        sendMyMessage: "Envoyer mon message",
        adminNotice: "Votre message sera traité par l'administration et le président de votre club (si applicable).",
        profileTitle: "Mon Profil",
        firstName: "Prénom",
        lastName: "Nom",
        phoneWhatsApp: "Téléphone / WhatsApp",
        birthDate: "Date de Naissance",
        favoriteClub: "Club Favori",
        selectClub: "Sélectionner un club",
        saveChanges: "Sauvegarder les modifications",
        profileUpdated: "Profil mis à jour avec succès !",
        membershipCard: "Ma Carte Membre",
        security: "Sécurité",
        newPassword: "Nouveau mot de passe",
        confirmPassword: "Confirmer le mot de passe",
        updateError: "Erreur lors de la mise à jour.",
        serverError: "Erreur serveur.",
        loadingProfile: "Chargement du profil...",
        sessionExpired: "Votre session a expiré ou est invalide. Veuillez vous reconnecter.",
        errorLoadingProfile: "Erreur lors du chargement du profil.",
        searchMember: "Rechercher un membre...",
        noUserFound: "Aucun utilisateur trouvé",
        startConversation: "Commencez la conversation avec",
        typeMessage: "Tapez votre message...",
        internalMessaging: "Messagerie Interne",
        selectMemberToChat: "Sélectionnez un membre dans la liste pour démarrer une discussion.",
        seen: "Vu",
        sent: "Envoyé",
        reclamationsTitle: "Demandes & Réclamations (Visiteurs)",
        noReclamations: "Aucune réclamation ou demande de partenariat pour le moment.",
        subjectInfo: "Demande Info",
        subjectPartnership: "Proposition Partenariat",
        subjectComplaint: "Réclamation / Plainte",
        newBadge: "NOUVEAU",
        markAsRead: "Marquer comme lu",
        delete: "Supprimer",
        receivedOn: "Reçu le",
        replyByEmail: "Répondre par Email",
        usersManagementTitle: "Gestion des Utilisateurs",
        selectAll: "Tout sélectionner",
        deselectAll: "Tout désélectionner",
        exportExcel: "Exporter Excel",
        member: "Membre",
        role: "Rôle",
        payment: "Paiement",
        phone: "Téléphone",
        status: "Statut",
        paid: "Payé",
        notPaid: "Non payé",
        pending: "En attente",
        approved: "Approuvé",
        rejected: "Refusé",
        confirmDeleteUser: "Supprimer cet utilisateur ?",
        clubsManagementTitle: "Gestion des Clubs",
        newClub: "Nouveau Club",
        editClub: "Modifier le Club",
        confirmDeleteClub: "Supprimer ce club ?",
        clubName: "Nom du Club",
        slugLabel: "Slug (url, ex: club-theatre)",
        description: "Description",
        addressLocal: "Adresse / Local",
        socialLinks: "Réseaux Sociaux",
        selectPresident: "Sélectionner un Président",
        activeMembersLabel: "Membres Actifs",
        partnerReviewsLabel: "Avis Partenaires",
        coverImage: "Image de Couverture",
        chooseImage: "Choisir une image",
        uploading: "Importation...",
        update: "Mettre à jour",
        createClub: "Créer le Club",
        manageMyPage: "Gérer ma page",
        identityDescription: "Identité & Description",
        clubDescription: "Description du club",
        activeMembersOfMonth: "Membres Actifs du Mois",
        selectMembersToHighlight: "Sélectionnez les membres à mettre en avant ce mois-ci.",
        addMember: "Ajouter un membre",
        chooseMember: "Choisir un membre",
        roleOptional: "Rôle (optionnel)",
        period: "Période",
        noFeaturedMembers: "Aucun membre mis en avant pour le moment.",
        reviewsTestimonials: "Avis & Témoignages",
        addReview: "Ajouter un avis",
        author: "Auteur",
        organization: "Organisation",
        reviewContent: "Contenu de l'avis",
        saveAllChanges: "Sauvegarder tous les changements",
        savingChanges: "Enregistrement en cours...",
        changesSaved: "Modifications enregistrées !",
        loadingMyClub: "Chargement de votre club...",
        noClubAssigned: "Aucun club ne vous a été assigné par l'administrateur.",
        selectMember: "-- Sélectionner --",
        actionsAttendance: "Actions & Présences",
        newAction: "Nouvelle Action",
        noActionsFound: "Aucune action trouvée. Créez-en une pour commencer.",
        addFirstAction: "Ajouter ma première action",
        confirmDeleteAction: "Êtes-vous sûr de vouloir supprimer cette action ?",
        manageAttendance: "Gérer la présence",
        addAction: "Ajouter une Action",
        actionTitle: "Titre de l'action",
        startDateLabel: "Date de début",
        startTimeLabel: "Heure locale",
        creating: "Création...",
        createAction: "Créer l'action",
        actions: "Actions",
        attendanceList: "Liste de Présence",
        present: "Présent",
        remark: "Remarque",
        noMemberFoundClub: "Aucun membre trouvé pour ce club.",
        detailsUpdated: "Détails mis à jour !",
        attendanceUpdated: "Présences mises à jour avec succès !",
        actionNotFound: "Action introuvable.",
        errorLoadingAction: "Erreur lors du chargement de l'action.",
        addRemark: "Ajouter une remarque...",
        contentsEventsTitle: "Contenus & Événements",
        noContentPublished: "Aucun contenu publié pour le moment.",
        editContent: "Modifier le contenu",
        newContent: "Nouveau Contenu",
        type: "Type",
        event: "Événement",
        formation: "Formation",
        photoGalleryLabel: "Photo / Galerie",
        videoYoutube: "Vidéo (YouTube, Instagram, Facebook, TikTok)",
        announcement: "Annonce",
        galleryPhotos: "Galerie Photos",
        imagesImported: "image(s) importée(s)",
        clearAll: "Vider tout",
        noPhotoSelected: "Aucune photo sélectionnée",
        videoUrl: "URL Vidéo (YouTube, Instagram, Facebook, TikTok)",
        externalLink: "Lien externe",
        submitForValidation: "Soumettre à validation",
        contentUpdated: "Contenu mis à jour !",
        contentSubmitted: "Contenu soumis avec succès !",
        uploadFailed: "L'importation du fichier a échoué.",
        waitUpload: "Veuillez attendre la fin de l'importation des images.",
        cover: "COUVERTURE",
        import: "Importer",
        at: "à",
        pollsModerationTitle: "Modération des Sondages",
        manageMyPolls: "Gérer mes Sondages",
        validatePollsDesc: "Validez les sondages créés par les présidents",
        createPollsDesc: "Créez des sondages pour engager votre communauté",
        createPoll: "Créer un Sondage",
        noPollFound: "Aucun sondage trouvé",
        public: "Public",
        membersOnlyLabel: "Membres",
        multiChoice: "Multichoix",
        singleChoiceLabel: "Unique",
        participants: "participants",
        reject: "Rejeter",
        approve: "Approuver",
        newPoll: "Nouveau Sondage",
        question: "Question",
        descriptionOptional: "Description (Optionnel)",
        options: "Options",
        addOption: "Ajouter une option",
        targetAudience: "Public cible",
        allVisitors: "Tous les visiteurs",
        voteType: "Type de vote",
        singleChoiceOption: "Un seul choix",
        multiChoiceOption: "Plusieurs choix possibles",
        submit: "Soumettre",
        confirmDeletePoll: "Supprimer ce sondage définitvement ?",
        national: "National",
        testimonialsTitle: "Avis & Témoignages",
        noTestimonials: "Aucun témoignage pour le moment.",
        confirmDeleteTestimonial: "Supprimer ce témoignage ?",
        approvedStatus: "Approuvé",
        waitingStatus: "En attente",
        pointsManagementTitle: "Gestion des Points",
        pointsManagementDesc: "Attribuez ou retirez des points bonus aux membres de votre club.",
        searchMemberPlaceholder: "Rechercher un membre par nom ou email...",
        bonusPoints: "Points Bonus",
        noMemberFound: "Aucun membre trouvé.",
        updateError: "Erreur lors de la mise à jour",
        technicalError: "Erreur technique",
        notificationsTitle: "Notifications",
        markAllAsRead: "Tout marquer comme lu",
        loadingNotifications: "Chargement des notifications...",
        errorLoading: "Erreur lors du chargement",
        serverConnectionError: "Erreur de connexion au serveur",
        retry: "Réessayer",
        noNotifications: "Vous n'avez aucune notification pour le moment.",
        markAsRead: "Marquer comme lu",
        viewDetails: "Voir les détails",
        usersManagementTitle: "Gestion des Utilisateurs",
        confirmDeleteUser: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?",
        selectAll: "Tout sélectionner",
        deselectAll: "Tout désélectionner",
        exportExcel: "Exporter en Excel",
        selectAtLeastOne: "Veuillez sélectionner au moins un utilisateur.",
        noClub: "Sans Club",
        registeredOn: "Inscrit le",
        userDetails: "Détails du membre",
        positionClub: "Position au club",
        adminNewPassword: "Nouveau mot de passe",
        leaveToKeepSame: "Laisser vide pour ne pas modifier",
        notAuthorizedRoleChange: "Vous n'êtes pas autorisé à modifier les rôles.",
        role: "Rôle",
        payment: "Paiement",
        phone: "Téléphone",
        phonePlaceholder: "N° Tel...",
        partnersManagementTitle: "Gestion des Partenaires",
        newPartner: "Nouveau Partenaire",
        confirmDeletePartner: "Supprimer ce partenaire ?",
        editPartner: "Modifier le Partenaire",
        partnerName: "Nom du Partenaire",
        websiteOptional: "Site Web (Optionnel)",
        displayOrder: "Ordre d'affichage",
        active: "Actif",
        partnerLogo: "Logo du Partenaire",
        chooseLogo: "Choisir un logo",
        visitWebsite: "Visiter le site",
        order: "Ordre",
        inactive: "Inactif",
        contentModerationTitle: "Modération des Contenus",
        addEvent: "Ajouter un événement",
        content: "Contenu",
        clubChef: "Club / Chef",
        sharing: "Partage",
        approveAction: "Approuver",
        refuseAction: "Refuser",
        home: "Accueil",
        bestOff: "Best Off",
        editContentTitle: "Modifier le Contenu",
        newContentTitle: "Nouveau Contenu",
        associateClub: "Associer au Club",
        selectClub: "Sélectionner un club",
        refused: "Refusé",
        photosSelect: "Photos (Sélectionnez une ou plusieurs)",
        importPhotos: "Importer Photos",
        videoUrlYoutube: "URL Vidéo (YouTube, Instagram, Facebook, TikTok)",
        externalLinkRegistration: "Lien externe / Inscription",
        saveChanges: "Enregistrer les modifications",
        createEvent: "Créer l'événement",
        contentSavedSuccess: "Contenu enregistré avec succès !",
        confirmDeleteContent: "Supprimer définitivement ce contenu ?",
        actionsModerationTitle: "Modération des Actions & News",
        manifestationPlan: "Plan de programme",
        addItem: "Ajouter un élément",
        globalDuration: "Durée globale",
        partsCount: "Nombre de parties",
        automaticOrdering: "Tri automatique",
        startTime: "Début",
        endTime: "Fin",
        durationMin: "Durée (min)",
        pause: "Pause",
        coffeeBreak: "Pause café",
        breakfast: "Petit déjeuner",
        lunch: "Déjeuner",
        dinner: "Dîner",
        remark: "Remarque",
        soiree: "Soirée",
        sleep: "Dormir",
        conference: "Conférence",
        formation: "Formation",
        dj_party: "DJ Party",
        spectacle: "Spectacle",
        speakerName: "Intervenant / Animateur",
        speakerPhoto: "Photo de l'intervenant",
        settingsTitle: "Paramètres de l'Association",

        // General
        loading: "Chargement...",
        error: "Erreur",
        back: "Retour",
        backToSite: "Retour au site",
        save: "Enregistrer",
        cancel: "Annuler",
        edit: "Modifier",
        optional: "Optionnel",
        name: "Nom",
        create: "Créer",
        preview: "Aperçu",
        nationalBoardTitle: "Bureau National",
        newMember: "Nouveau Membre",
        confirmDeleteMember: "Supprimer ce membre du bureau ?",
        editMember: "Modifier le Membre",
        roleFunction: "Fonction / Rôle",
        rolePlaceholder: "ex: Président, Secrétaire...",
        memberPhoto: "Photo du Membre",
        choosePhoto: "Choisir une photo",
        addToBoard: "Ajouter au bureau",
        aboutManagement: "Gestion À Propos",
        aboutManagementTitle: "Gestion de la page À Propos",
        newSection: "Nouvelle Section",
        confirmDeleteSection: "Supprimer cette section ?",
        editSection: "Modifier la Section",
        objective: "Objectif",
        domain: "Domaine",
        value: "Valeur",
        icon: "Icône",
        images: "Images / Galerie",
        imageLayout: "Disposition des images",
        layoutBottom: "Bas",
        layoutTop: "Haut",
        layoutLeft: "Gauche",
        layoutRight: "Droite",
        layoutGrid: "Grille",
        layoutGrid: "Grille",
        add: "Ajouter",
        buttonText: "Texte du bouton (Optionnel)",
        buttonLink: "Lien du bouton (Optionnel)",
        buttonTextPlaceholder: "ex: Rejoindre le groupe",
        footerManagement: "Gestion du Pied de Page",
        footerManagementDesc: "Personnalisez les informations affichées dans le pied de page du site.",
        footerDescription: "Description / À propos",
        footerDescriptionPlaceholder: "Une brève description de l'association...",
        addressLocal: "Adresse / Local",
        socialLinks: "Réseaux Sociaux",
        quickLinks: "Liens Rapides",
        text: "Texte",
        ourLocations: "Nos Implantations",
        noAddress: "Adresse non renseignée",
        meetingTA: "Réunion TA",
        createMeeting: "Créer une réunion",
        scheduleMeeting: "Programmer une réunion",
        meetingDateTime: "Date et Heure",
        lateLimitMinutes: "Limite de retard (min)",
        participants: "Participants",
        meetingLink: "Lien",
        joinMeeting: "Rejoindre",
        noMeetings: "Aucune réunion prévue",
        meetingConfirmed: "Réunion créée avec succès !",
        meetingNotificationTitle: "Nouvelle Réunion TA",
        meetingNotificationMessage: "Vous êtes invité à la réunion : {title}",
        meetingSettings: "Gestion Réunion TA",
        authorizedRoles: "Rôles autorisés",
        authorizedUsers: "Utilisateurs spécifiques",
        pointsAwarded: "Point de présence attribué !",
        directMeeting: "Direct (immédiat)",
        scheduledMeeting: "Programmé",
        selectClubs: "Sélectionner les clubs",
        selectMembers: "Sélectionner des membres",
        meetingDeleted: "Réunion supprimée",
        confirmDeleteMeeting: "Supprimer cette réunion ?"
    },
    en: {
        // ATA Waves
        ataWaves: "ATA Waves",
        latestEpisodes: "Latest Episodes",
        episodesCount: "episode(s)",
        noEpisodes: "No episodes available right now.",
        contentNotAvailable: "Content Not Available",
        pageNotPublished: "The ATA Waves page is not published right now.",
        video: "Video",
        by: "By",
        publishedOn: "Published on",
        unsupportedPlayer: "Player not supported for this platform",
        openVideoDirectly: "Click the button below to view the episode directly on its original platform.",
        openVideoBtn: "Open video",
        teamAta: "ATA Team",

        // Navbar
        home: "Home",
        about: "About",
        clubs: "Clubs",
        bestOff: "Best Off",
        contact: "Contact",
        dashboard: "Dashboard",
        connexion: "Login",
        signup: "Sign Up",
        logout: "Logout",
        installApp: "Install App",

        // Auth
        loginTitle: "Login",
        signupTitle: "Sign Up",
        welcomeBack: "Happy to see you again!",
        accountCreatedSuccess: "Your account has been created successfully. Please log in.",
        email: "Email",
        password: "Password",
        forgotPassword: "Forgot password?",
        logInProgress: "Logging in...",
        loginBtn: "Login",
        noAccountYet: "Don't have an account yet?",
        joinAta: "Join ATA",
        createAccountDesc: "Create your member account and join the adventure",
        confirmPassword: "Confirm password",
        passwordsDontMatch: "Passwords do not match.",
        signupProgress: "Creating account...",
        signupNotice: "Note: Your account must be approved by an administrator before you can access all features.",
        chooseClub: "Choose a club",
        selectFavoriteClub: "Select your favorite club",
        alreadyHaveAccount: "Already have an account?",
        loginAction: "Log In",
        signupAction: "Sign Up",
        forgotPasswordTitle: "Forgot Password",
        forgotPasswordSubtitle: "Enter your email address to receive a reset link.",
        sendResetLink: "Send Link",
        sendingLink: "Sending...",
        backToLogin: "Back to Login",
        newPasswordTitle: "New Password",
        newPasswordSubtitle: "Enter your new password below.",
        resetPasswordBtn: "Reset Password",
        resettingBtn: "Resetting...",
        invalidToken: "Invalid or missing reset token.",
        requestNewLink: "Request a new link.",
        resetSuccessRedirect: "Your password has been reset. Redirecting to login page...",
        meetingTA: "TA Meeting",
        createMeeting: "Create Meeting",
        scheduleMeeting: "Schedule Meeting",
        meetingDateTime: "Date and Time",
        lateLimitMinutes: "Late limit (min)",
        participants: "Participants",
        meetingLink: "Link",
        joinMeeting: "Join",
        noMeetings: "No meetings scheduled",
        meetingConfirmed: "Meeting created successfully!",
        meetingNotificationTitle: "New TA Meeting",
        meetingNotificationMessage: "You are invited to the meeting: {title}",
        meetingSettings: "TA Meeting Management",
        authorizedRoles: "Authorized Roles",
        authorizedUsers: "Specific Users",
        pointsAwarded: "Attendance point awarded!",
        directMeeting: "Direct (immediate)",
        scheduledMeeting: "Scheduled",
        selectClubs: "Select clubs",
        selectMembers: "Select members",
        meetingDeleted: "Meeting deleted",
        confirmDeleteMeeting: "Delete this meeting?",

        // Home
        brandName: "Touches D'Art",
        heroTitle: "Express your creativity with",
        heroSubtitle: "Cultural, artistic and academic association. Join a passionate community and participate in innovative projects.",
        discoverClubs: "Discover clubs",
        joinUs: "Join Us",
        accessDashboard: "Access Dashboard",
        newsEvents: "News & Events",
        upcomingActivities: "Don't miss our clubs' upcoming events.",
        featured: "Featured",
        artCulture: "Art & Culture",
        artCultureDesc: "Workshops and events to promote art in all its forms.",
        community: "Community",
        communityDesc: "A network of students and enthusiasts united by creativity.",
        excellence: "Excellence",
        excellenceDesc: "High-level academic and artistic projects.",
        ourClubs: "Our Clubs",
        viewPage: "View Page",
        noDescription: "No description available at the moment.",
        learnMore: "Learn more",

        // Best Off
        bestOffSubtitle: "Explore the highlights and exceptional achievements of the Touches D'Art community.",
        bestOffEmpty: "The gallery is currently being prepared. Come back soon!",

        // Search
        searchPlaceholder: "Search on page...",
        results: "results",

        // Clubs
        ourClubsTitle: "Our Clubs",
        ourClubsSubtitle: "Discover the richness of our activity poles. There is bound to be a club for you.",
        noClubs: "No clubs registered yet. Check the Administration area.",
        clubATA: "ATA Club",
        backToClubs: "Back to clubs",
        aboutClub: "About the club",
        followUs: "Follow us",
        activeMembers: "Active Members",
        realTime: "Real time",
        birthdayTitle: "It's a party! 🎂",
        birthdaySubtitle: "Happy birthday to our exceptional member:",
        birthdaySubtitlePlural: "Happy birthday to our exceptional members:",
        birthdaySubtitleDesc: "Let's celebrate our exceptional members together!",
        noBirthdayToday: "No birthdays today!",
        comeBackTomorrow: "Come back tomorrow to celebrate our members.",
        itsTheirDay: "Today is their day!",
        president: "President",
        nationalBoardMember: "National Board Member",
        eventsFormations: "Events & Training",
        photoGallery: "Photo Gallery",
        videosCreations: "Videos & Creations",
        testimonialsTitle: "Reviews & Testimonials",
        leaveReview: "Leave a review",
        close: "Close",
        yourName: "Your name (Optional if member)",
        fullName: "Full name",
        rating: "Rating",
        yourMessage: "Your message",
        shareExperience: "Share your experience...",
        sendReview: "Send my review",
        reviewSuccess: "Thank you! Your review has been sent and will be visible after validation.",
        noReviews: "No reviews yet. Be the first!",
        anonymous: "Anonymous",

        // About
        aboutTitle: "Touches D'Art",
        aboutDesc: "\"Touches d'Art\" is a cultural association that welcomes a group of creative young people with varied talents, such as event organization, public animation, journalism and media, painting, singing and many other forms of art and talents.",
        objectivesTitle: "Association Objectives",
        obj1: "Contribute to anchoring the values of volunteering and the spirit of initiative in youth environments.",
        obj2: "Support domestic tourism and promote tourist sites.",
        obj3: "Promote historical monuments in Tunisia in coordination with officials.",
        domainsTitle: "Our Fields of Activity",
        domain1Title: "Cultural & Artistic Field",
        domain1Desc: "The club focuses on the cultural aspect, particularly among young people, by organizing cultural activities aimed at enriching the cultural scene and providing artistic touches.",
        domain2Title: "Social & Educational Field",
        domain2Desc: "We create coherence between the name and the theme of the association by promoting collective learning and the sharing of know-how between members.",
        domain3Title: "Recreational Field",
        domain3Desc: "Moments of relaxation for members, while opening our doors to the public through the organization of various activities and recreational outings.",
        valuesTitle: "Our Values",
        value1Title: "Excellence",
        value1Desc: "Provide high-quality academic and artistic content and events.",
        value2Title: "Passion",
        value2Desc: "Encourage everyone to fully live their interests and share them.",
        value3Title: "Innovation",
        value3Desc: "Constantly push boundaries by merging traditional art and modernity.",
        boardTitle: "National Board",
        pollsTitle: "We value your opinion",

        // Contact
        contactTitle: "Contact Us",
        contactSubtitle: "A question, a proposal or a complaint? Write to us.",
        subject: "Subject",
        selectSubject: "Select a subject",
        info: "Information request",
        partnership: "Partnership proposal",
        complaint: "Complaint",
        other: "Other",
        message: "Message",
        messagePlaceholder: "Your message...",
        yourEmail: "Your Email",
        send: "Send message",
        sending: "Sending...",
        success: "Message sent successfully! We will reply soon.",

        // Modal
        clubLabel: "Club",
        noDescAvailable: "No description available.",
        featuredPhoto: "Featured Photo",
        eventVideo: "Event Video",
        photoAlbum: "Photo Album",
        participate: "Participate / See more",

        // Polls
        resultsLabel: "Results",
        votesLabel: "votes",
        thanksParticipation: "Thank you for your participation!",
        voteBtn: "Vote",
        votingBtn: "Sending...",
        multipleChoices: "Multiple choices allowed",
        singleChoice: "Single choice only",
        membersOnly: "Members only",
        openToAll: "Open to all",
        voteError: "An error occurred while voting",

        // Dashboard
        dashboardTitle: "Dashboard",
        dashboardOverview: "Overview",
        myProfile: "My Profile",
        notifications: "Notifications",
        messaging: "Messaging",
        memberVoice: "Member Voice",
        voiceManagement: "Member Voice Management",
        demandsReclamations: "Demands & Complaints",
        users: "Users",
        clubsManagement: "Clubs Management",
        membersManagement: "Members Management",
        nationalBoard: "National Board",
        partners: "Partners",
        contents: "Contents",
        actionsModeration: "Actions Moderation",
        pollsModeration: "Polls Moderation",
        actionsManagement: "Actions Management",
        generalSettings: "General Settings",
        myClub: "My Club",
        pageSettings: "Page Settings",
        contentsEvents: "Contents & Events",
        actionsAttendance: "Actions & Attendance",
        reviewsTestimonials: "Reviews & Testimonials",
        polls: "Polls",
        totalActions: "Total Actions",
        recentActivity: "Recent Activity",
        engagementPerformance: "Engagement & Performance",
        points: "pts",
        closeProfile: "Close profile",
        noActivityData: "Insufficient activity data",
        clubNews: "Clubs News",
        next10Days: "(Next 10 days)",
        memberVoiceTitle: "Member Voice",
        memberVoiceSubtitle: "A secure space to share your problems, concerns or remarks. Your voice matters to us.",
        yourMessageLabel: "Your message / problem description",
        messagePlaceholderVoice: "Describe here what you want to tell us...",
        submissionMode: "How would you like to submit this message?",
        anonymousMode: "Anonymous",
        identifiedMode: "Identified",
        messageSentSuccess: "Thank you for sharing",
        messageSentDesc: "Your message has been transmitted in complete confidentiality. We attach great importance to your well-being within Touches D'Art.",
        sendAnother: "Send another message",
        sendingVoice: "Sending...",
        sendMyMessage: "Send my message",
        adminNotice: "Your message will be processed by the administration and the president of your club (if applicable).",
        profileTitle: "My Profile",
        firstName: "First Name",
        lastName: "Last Name",
        phoneWhatsApp: "Phone / WhatsApp",
        birthDate: "Birth Date",
        favoriteClub: "Favorite Club",
        selectClub: "Select a club",
        saveChanges: "Save changes",
        profileUpdated: "Profile updated successfully!",
        membershipCard: "My Membership Card",
        security: "Security",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
        updateError: "Error during update.",
        serverError: "Server error.",
        loadingProfile: "Loading profile...",
        sessionExpired: "Your session has expired or is invalid. Please log in again.",
        errorLoadingProfile: "Error loading profile.",
        searchMember: "Search for a member...",
        noUserFound: "No user found",
        startConversation: "Start a conversation with",
        typeMessage: "Type your message...",
        internalMessaging: "Internal Messaging",
        selectMemberToChat: "Select a member from the list to start a discussion.",
        seen: "Seen",
        sent: "Sent",
        reclamationsTitle: "Demands & Complaints (Visitors)",
        noReclamations: "No complaints or partnership requests at the moment.",
        subjectInfo: "Info Request",
        subjectPartnership: "Partnership Proposal",
        subjectComplaint: "Complaint / Claim",
        newBadge: "NEW",
        markAsRead: "Mark as read",
        delete: "Delete",
        receivedOn: "Received on",
        replyByEmail: "Reply by Email",
        usersManagementTitle: "Users Management",
        selectAll: "Select All",
        deselectAll: "Deselect All",
        exportExcel: "Export Excel",
        registeredOn: "Member since",
        userDetails: "Member Details",
        positionClub: "Position in the club",
        adminNewPassword: "New Password",
        leaveToKeepSame: "Leave blank to keep current",
        notAuthorizedRoleChange: "You are not authorized to change roles.",
        member: "Member",
        role: "Role",
        payment: "Payment",
        phone: "Phone",
        status: "Status",
        paid: "Paid",
        notPaid: "Not Paid",
        pending: "Pending",
        approved: "Approved",
        rejected: "Rejected",
        confirmDeleteUser: "Delete this user?",
        partnersManagementTitle: "Partners Management",
        newPartner: "New Partner",
        confirmDeletePartner: "Delete this partner?",
        editPartner: "Edit Partner",
        partnerName: "Partner Name",
        websiteOptional: "Website (Optional)",
        displayOrder: "Display Order",
        active: "Active",
        partnerLogo: "Partner Logo",
        chooseLogo: "Choose a logo",
        visitWebsite: "Visit website",
        order: "Order",
        inactive: "Inactive",
        clubsManagementTitle: "Clubs Management",
        newClub: "New Club",
        editClub: "Edit Club",
        confirmDeleteClub: "Delete this club?",
        clubName: "Club Name",
        slugLabel: "Slug (url, e.g.: theatre-club)",
        description: "Description",
        addressLocal: "Address / Location",
        socialLinks: "Social Networks",
        selectPresident: "Select a President",
        activeMembersLabel: "Active Members",
        partnerReviewsLabel: "Partner Reviews",
        coverImage: "Cover Image",
        chooseImage: "Choose an image",
        uploading: "Uploading...",
        update: "Update",
        createClub: "Create Club",
        manageMyPage: "Manage my page",
        identityDescription: "Identity & Description",
        clubDescription: "Club description",
        activeMembersOfMonth: "Active Members of the Month",
        selectMembersToHighlight: "Select members to highlight this month.",
        addMember: "Add a member",
        chooseMember: "Choose a member",
        roleOptional: "Role (optional)",
        period: "Period",
        noFeaturedMembers: "No featured members for now.",
        reviewsTestimonials: "Reviews & Testimonials",
        addReview: "Add a review",
        author: "Author",
        organization: "Organization",
        reviewContent: "Review content",
        saveAllChanges: "Save all changes",
        savingChanges: "Saving changes...",
        changesSaved: "Changes saved!",
        loadingMyClub: "Loading your club...",
        noClubAssigned: "No club has been assigned to you by the administrator.",
        selectMember: "-- Select --",
        actionsAttendance: "Actions & Attendance",
        newAction: "New Action",
        noActionsFound: "No actions found. Create one to start.",
        addFirstAction: "Add my first action",
        confirmDeleteAction: "Are you sure you want to delete this action?",
        manageAttendance: "Manage attendance",
        addAction: "Add an Action",
        actionTitle: "Action Title",
        startDateLabel: "Start Date",
        startTimeLabel: "Local Time",
        creating: "Creating...",
        createAction: "Create action",
        actions: "Actions",
        attendanceList: "Attendance List",
        present: "Present",
        remark: "Remark",
        noMemberFoundClub: "No member found for this club.",
        detailsUpdated: "Details updated!",
        attendanceUpdated: "Attendance updated successfully!",
        actionNotFound: "Action not found.",
        errorLoadingAction: "Error loading action.",
        addRemark: "Add a remark...",
        contentsEventsTitle: "Contents & Events",
        noContentPublished: "No content published yet.",
        editContent: "Edit content",
        newContent: "New Content",
        type: "Type",
        event: "Event",
        formation: "Training",
        photoGalleryLabel: "Photo / Gallery",
        videoYoutube: "Video (YouTube, Instagram, Facebook, TikTok)",
        announcement: "Announcement",
        galleryPhotos: "Photo Gallery",
        imagesImported: "image(s) imported",
        clearAll: "Clear all",
        noPhotoSelected: "No photo selected",
        videoUrl: "Video URL (YouTube, Instagram, Facebook, TikTok)",
        externalLink: "External link",
        submitForValidation: "Submit for validation",
        contentUpdated: "Content updated!",
        contentSubmitted: "Content submitted successfully!",
        uploadFailed: "File upload failed.",
        waitUpload: "Please wait for images to finish uploading.",
        cover: "COVER",
        import: "Import",
        at: "at",
        pollsModerationTitle: "Polls Moderation",
        manageMyPolls: "Manage my Polls",
        validatePollsDesc: "Validate polls created by presidents",
        createPollsDesc: "Create polls to engage your community",
        createPoll: "Create a Poll",
        noPollFound: "No poll found",
        public: "Public",
        membersOnlyLabel: "Members",
        multiChoice: "Multi-choice",
        singleChoiceLabel: "Single",
        participants: "participants",
        reject: "Reject",
        approve: "Approve",
        newPoll: "New Poll",
        question: "Question",
        descriptionOptional: "Description (Optional)",
        options: "Options",
        addOption: "Add an option",
        targetAudience: "Target audience",
        allVisitors: "All visitors",
        voteType: "Vote type",
        singleChoiceOption: "Single choice only",
        multiChoiceOption: "Multiple choices allowed",
        submit: "Submit",
        confirmDeletePoll: "Delete this poll permanently?",
        national: "National",
        testimonialsTitle: "Reviews & Testimonials",
        noTestimonials: "No testimonials yet.",
        confirmDeleteTestimonial: "Delete this testimonial?",
        approvedStatus: "Approved",
        waitingStatus: "Pending",
        pointsManagementTitle: "Points Management",
        pointsManagementDesc: "Assign or remove bonus points for your club members.",
        searchMemberPlaceholder: "Search member by name or email...",
        bonusPoints: "Bonus Points",
        noMemberFound: "No member found.",
        updateError: "Update error",
        technicalError: "Technical error",

        // General
        loading: "Loading...",
        error: "Error",
        back: "Back",
        backToSite: "Back to Site",
        save: "Save",
        cancel: "Cancel",
        edit: "Edit",
        optional: "Optional",
        name: "Name",
        create: "Create",
        preview: "Preview",
        contentModerationTitle: "Content Moderation",
        addEvent: "Add Event",
        content: "Content",
        clubChef: "Club / Chief",
        sharing: "Sharing",
        approveAction: "Approve",
        refuseAction: "Refuse",
        home: "Home",
        bestOff: "Best Off",
        editContentTitle: "Edit Content",
        newContentTitle: "New Content",
        associateClub: "Associate with Club",
        selectClub: "Select a club",
        refused: "Refused",
        photosSelect: "Photos (Select one or more)",
        importPhotos: "Import Photos",
        videoUrlYoutube: "Video URL (YouTube)",
        externalLinkRegistration: "External Link / Registration",
        saveChanges: "Save Changes",
        createEvent: "Create Event",
        contentSavedSuccess: "Content saved successfully!",
        confirmDeleteContent: "Permanently delete this content?",
        actionsModerationTitle: "Actions & News Moderation",
        manifestationPlan: "Manifestation Plan",
        addItem: "Add Item",
        globalDuration: "Global Duration",
        partsCount: "Parts Count",
        automaticOrdering: "Automatic Ordering",
        startTime: "Start",
        endTime: "End",
        durationMin: "Duration (min)",
        pause: "Pause",
        coffeeBreak: "Coffee Break",
        breakfast: "Breakfast",
        lunch: "Lunch",
        dinner: "Dinner",
        remark: "Remark",
        soiree: "Evening",
        sleep: "Sleep",
        conference: "Conference",
        formation: "Training",
        dj_party: "DJ Party",
        spectacle: "Show",
        speakerName: "Speaker / Animator",
        speakerPhoto: "Speaker Photo",
        settingsTitle: "Association Settings",
        nationalBoardTitle: "National Board",
        newMember: "New Member",
        confirmDeleteMember: "Delete this board member?",
        editMember: "Edit Member",
        roleFunction: "Function / Role",
        rolePlaceholder: "e.g.: President, Secretary...",
        memberPhoto: "Member Photo",
        choosePhoto: "Choose a photo",
        addToBoard: "Add to board",
        aboutManagement: "About Management",
        aboutManagementTitle: "About Page Management",
        newSection: "New Section",
        confirmDeleteSection: "Delete this section?",
        editSection: "Edit Section",
        objective: "Objective",
        domain: "Domain",
        value: "Value",
        icon: "Icon",
        images: "Images / Gallery",
        imageLayout: "Image Layout",
        layoutBottom: "Bottom",
        layoutTop: "Top",
        layoutLeft: "Left",
        layoutRight: "Right",
        layoutGrid: "Grid",
        layoutGrid: "Grid",
        add: "Add",
        buttonText: "Button Text (Optional)",
        buttonLink: "Button Link (Optional)",
        buttonTextPlaceholder: "e.g.: Join group",
        footerManagement: "Footer Management",
        footerManagementDesc: "Customize the information displayed in the site footer.",
        footerDescription: "Description / About",
        footerDescriptionPlaceholder: "A brief description of the association...",
        addressLocal: "Address / Location",
        socialLinks: "Social Networks",
        quickLinks: "Quick Links",
        text: "Text",
        ourLocations: "Our Locations",
        noAddress: "Address not provided"
    },
    ar: {
        // Navbar
        home: "الرئيسية",
        about: "من نحن",
        clubs: "النوادي",
        bestOff: "الأفضل",
        contact: "اتصل بنا",
        dashboard: "لوحة القيادة",
        connexion: "تسجيل الدخول",
        signup: "إنشاء حساب",
        logout: "تسجيل الخروج",
        installApp: "تثبيت التطبيق",

        // Auth
        loginTitle: "تسجيل الدخول",
        signupTitle: "إنشاء حساب",
        welcomeBack: "سعيد برؤيتك مرة أخرى!",
        accountCreatedSuccess: "تم إنشاء حسابك بنجاح. يرجى تسجيل الدخول.",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        forgotPassword: "هل نسيت كلمة المرور؟",
        logInProgress: "جاري تسجيل الدخول...",
        loginBtn: "تسجيل الدخول",
        noAccountYet: "ليس لديك حساب بعد؟",
        joinAta: "انضم إلى ATA",
        createAccountDesc: "أنشئ حسابك كعضو وشارك في المغامرة",
        confirmPassword: "تأكيد كلمة المرور",
        passwordsDontMatch: "كلمات المرور غير متطابقة.",
        signupProgress: "جاري إنشاء الحساب...",
        signupNotice: "ملاحظة: يجب الموافقة على حسابك من قبل المسؤول قبل أن تتمكن من الوصول إلى جميع الميزات.",
        chooseClub: "اختر نادياً",
        selectFavoriteClub: "اختر ناديك المفضل",
        alreadyHaveAccount: "لديك حساب بالفعل؟",
        loginAction: "تسجيل الدخول",
        signupAction: "إنشاء حساب",
        forgotPasswordTitle: "نسيت كلمة المرور",
        forgotPasswordSubtitle: "أدخل بريدك الإلكتروني لتلقي رابط إعادة التعيين.",
        sendResetLink: "إرسال الرابط",
        sendingLink: "جاري الإرسال...",
        backToLogin: "العودة لتسجيل الدخول",
        newPasswordTitle: "كلمة مرور جديدة",
        newPasswordSubtitle: "أدخل كلمة المرور الجديدة أدناه.",
        resetPasswordBtn: "إعادة تعيين كلمة المرور",
        resettingBtn: "جاري إعادة التعيين...",
        invalidToken: "رابط إعادة التعيين غير صالح أو مفقود.",
        requestNewLink: "طلب رابط جديد.",
        resetSuccessRedirect: "تمت إعادة تعيين كلمة المرور بنجاح. جاري توجيهك لصفحة تسجيل الدخول...",

        ataWaves: "أمواج أطا",
        latestEpisodes: "أحدث الحلقات",
        episodesCount: "حلقة/حلقات",
        noEpisodes: "لا توجد حلقات متاحة في الوقت الحالي.",
        contentNotAvailable: "المحتوى غير متوفر",
        pageNotPublished: "صفحة ATA Waves غير منشورة حالياً.",
        video: "فيديو",
        by: "بواسطة",
        publishedOn: "نُشر في",
        unsupportedPlayer: "المشغل غير مدعوم على هذه المنصة",
        openVideoDirectly: "انقر على الزر أدناه لمشاهدة الحلقة مباشرة على المنصة الأصلية.",
        openVideoBtn: "فتح الفيديو",
        teamAta: "فريق أطا",

        // Home
        brandName: "لمسات فنّية",
        heroTitle: "عبر عن إبداعك مع",
        heroSubtitle: "جمعية ثقافية وفنية وأكاديمية. انضم إلى مجتمع شغوف وشارك في مشاريع مبتكرة.",
        discoverClubs: "اكتشف النوادي",
        joinUs: "انضم إلينا",
        accessDashboard: "دخول لوحة القيادة",
        newsEvents: "الأخبار والفعاليات",
        upcomingActivities: "فعاليات نوادينا التي لا يجب تفويتها.",
        featured: "في الواجهة",
        artCulture: "الفن والثقافة",
        artCultureDesc: "ورش عمل وفعاليات لتعزيز الفن بجميع أشكاله.",
        community: "المجتمع",
        communityDesc: "شبكة من الطلاب والشغوفين يجمعهم الإبداع.",
        excellence: "التميز",
        excellenceDesc: "مشاريع أكاديمية وفنية رفيعة المستوى.",
        ourClubs: "نوادينا",
        viewPage: "عرض الصفحة",
        noDescription: "لا يوجد وصف متاح حالياً.",
        learnMore: "اقرأ المزيد",

        // Best Off
        bestOffSubtitle: "استكشف أبرز اللحظات والإنجازات الاستثنائية لمجتمع لمسات فنّية.",
        bestOffEmpty: "المعرض قيد التحضير. عد قريباً!",

        // Search
        searchPlaceholder: "بحث في الصفحة...",
        results: "نتائج",

        // Clubs
        ourClubsTitle: "نوادينا",
        ourClubsSubtitle: "اكتشف ثراء أقطاب نشاطنا. بالتأكيد هناك نادٍ مناسب لك.",
        noClubs: "لم يتم تسجيل أي نوادي بعد. راجع منطقة الإدارة.",
        clubATA: "نادي ATA",
        backToClubs: "العودة إلى النوادي",
        aboutClub: "حول النادي",
        followUs: "تابعنا",
        activeMembers: "الأعضاء النشطون",
        realTime: "الوقت الفعلي",
        birthdayTitle: "إنه وقت الاحتفال! 🎂",
        birthdaySubtitle: "عيد ميلاد سعيد لعضونا المتميز:",
        birthdaySubtitlePlural: "عيد ميلاد سعيد لأعضائنا المتميزين:",
        birthdaySubtitleDesc: "دعونا نحتفل معاً بأعضائنا المتميزين!",
        noBirthdayToday: "لا توجد أعياد ميلاد اليوم!",
        comeBackTomorrow: "عد غداً للاحتفال بأعضائنا.",
        itsTheirDay: "اليوم هو يومهم المميز!",
        president: "الرئيس",
        nationalBoardMember: "عضو مكتب وطني",
        eventsFormations: "الفعاليات والتكوينات",
        photoGallery: "معرض الصور",
        videosCreations: "الفيديوهات والإنجازات",
        testimonialsTitle: "الآراء والشهادات",
        leaveReview: "اترك رأياً",
        close: "إغلاق",
        yourName: "اسمك (اختياري إذا كنت عضواً)",
        fullName: "الاسم الكامل",
        rating: "التقييم",
        yourMessage: "رسالتك",
        shareExperience: "شارك تجربتك...",
        sendReview: "إرسال رأيي",
        reviewSuccess: "شكراً لك! تم إرسال رأيك وسيظهر بعد التحقق منه.",
        noReviews: "لا توجد آراء حالياً. كن أول من يعلق!",
        anonymous: "مجهول",

        // About
        aboutTitle: "لمسات فنّية",
        aboutDesc: "\"لمسات فنّية\" هي جمعية ثقافية تستقبل مجموعة من الشباب المبدعين ذوي المواهب المتنوعة، مثل تنظيم الفعاليات، وتنشيط الجمهور، والصحافة والإعلام، والرسم، والغناء والعديد من أشكال الفن والمواهب الأخرى.",
        objectivesTitle: "أهداف الجمعية",
        obj1: "المساهمة في ترسيخ قيم التطوع وروح المبادرة في أوساط الشباب.",
        obj2: "دعم السياحة الداخلية والترويج للمواقع السياحية.",
        obj3: "الترويج للمعالم التاريخية في تونس بالتنسيق مع المسؤولين.",
        domainsTitle: "مجالات نشاطنا",
        domain1Title: "المجال الثقافي والفني",
        domain1Desc: "يركز النادي على الجانب الثقافي، خاصة لدى الشباب، من خلال تنظيم أنشطة ثقافية تهدف إلى إثراء المشهد الثقافي وتقديم لمسات فنية.",
        domain2Title: "المجال الاجتماعي والتربوي",
        domain2Desc: "نخلق انسجاماً بين اسم الجمعية وموضوعها من خلال تعزيز التعلم الجماعي وتبادل الخبرات بين الأعضاء.",
        domain3Title: "المجال الترفيهي",
        domain3Desc: "لحظات من الاسترخاء للأعضاء، مع فتح أبوابنا للجمهور من خلال تنظيم أنشطة متنوعة ورحلات ترفيهية.",
        valuesTitle: "قيمنا",
        value1Title: "التميز",
        value1Desc: "تقديم محتويات وفعاليات ذات جودة أكاديمية وفنية عالية.",
        value2Title: "الشغف",
        value2Desc: "تشجيع الجميع على عيش اهتماماتهم بالكامل ومشاركتها.",
        value3Title: "الابتكار",
        value3Desc: "دفع الحدود باستمرار من خلال دمج الفن التقليدي والحداثة.",
        boardTitle: "المكتب الوطني",
        pollsTitle: "رأيكم يهمنا",

        // Contact
        contactTitle: "اتصل بنا",
        contactSubtitle: "سؤال، اقتراح أو شكوى? اكتب لنا.",
        subject: "الموضوع",
        selectSubject: "اختر موضوعاً",
        info: "طلب معلومات",
        partnership: "اقتراح شراكة",
        complaint: "شكوى",
        other: "آخر",
        message: "الرسالة",
        messagePlaceholder: "رسالتك...",
        yourEmail: "بريدك الإلكتروني",
        send: "إرسال الرسالة",
        sending: "جاري الإرسال...",
        success: "تم إرسال الرسالة بنجاح! سنرد عليك قريباً.",

        // Modal
        clubLabel: "النادي",
        noDescAvailable: "لا يوجد وصف متاح.",
        featuredPhoto: "الصورة المميزة",
        eventVideo: "فيديو الفعالية",
        photoAlbum: "ألبوم الصور",
        participate: "المشاركة / عرض المزيد",

        // Polls
        resultsLabel: "النتائج",
        votesLabel: "أصوات",
        thanksParticipation: "شكراً لمشاركتك!",
        voteBtn: "تصويت",
        votingBtn: "جاري الإرسال...",
        multipleChoices: "يسمح بخيارات متعددة",
        singleChoice: "خيار واحد فقط",
        membersOnly: "للأعضاء فقط",
        openToAll: "مفتوح للجميع",
        voteError: "حدث خطأ أثناء التصويت",

        // Dashboard
        dashboardTitle: "لوحة القيادة",
        dashboardOverview: "نظرة عامة",
        myProfile: "ملفي الشخصي",
        notifications: "الإشعارات",
        messaging: "المراسلة",
        memberVoice: "صوت الأعضاء",
        voiceManagement: "إدارة صوت الأعضاء",
        demandsReclamations: "الطلبات والشكاوى",
        users: "المستخدمين",
        clubsManagement: "إدارة النوادي",
        membersManagement: "إدارة الأعضاء",
        nationalBoard: "المكتب الوطني",
        partners: "الشركاء",
        contents: "المحتويات",
        actionsModeration: "مراجعة الأنشطة",
        pollsModeration: "مراجعة الاستطلاعات",
        actionsManagement: "إدارة الأنشطة",
        generalSettings: "الإعدادات العامة",
        myClub: "ناديي",
        pageSettings: "إعدادات الصفحة",
        contentsEvents: "المحتويات والفعاليات",
        actionsAttendance: "الأنشطة والحضور",
        reviewsTestimonials: "الآراء والشهادات",
        polls: "الاستطلاعات",
        totalActions: "إجمالي الأنشطة",
        recentActivity: "النشاط الأخير",
        engagementPerformance: "التفاعل والأداء",
        points: "نقطة",
        closeProfile: "إغلاق الملف الشخصي",
        noActivityData: "بيانات النشاط غير كافية",
        clubNews: "أخبار النوادي",
        next10Days: "(الـ 10 أيام القادمة)",
        memberVoiceTitle: "صوت الأعضاء",
        memberVoiceSubtitle: "مساحة آمنة لمشاركة مشاكلك أو مخاوفك أو ملاحظاتك. صوتك يهمنا.",
        yourMessageLabel: "رسالتك / وصف المشكلة",
        messagePlaceholderVoice: "صف هنا ما تريد إخبارنا به...",
        submissionMode: "كيف ترغب في إرسال هذه الرسالة؟",
        anonymousMode: "مجهول",
        identifiedMode: "محدد الهوية",
        messageSentSuccess: "شكراً لمشاركتك",
        messageSentDesc: "تم إرسال رسالتك بكل سرية. نحن نولي أهمية كبيرة لرفاهيتك داخل لمسات فنّية.",
        sendAnother: "إرسال رسالة أخرى",
        sendingVoice: "جاري الإرسال...",
        sendMyMessage: "إرسال رسالتي",
        adminNotice: "سيتم معالجة رسالتك من قبل الإدارة ورئيس ناديك (إن وجد).",
        profileTitle: "ملفي الشخصي",
        firstName: "الاسم الأول",
        lastName: "اللقب",
        phoneWhatsApp: "الهاتف / واتساب",
        birthDate: "تاريخ الميلاد",
        favoriteClub: "النادي المفضل",
        selectClub: "اختر نادياً",
        saveChanges: "حفظ التغييرات",
        profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
        membershipCard: "بطاقة العضوية",
        security: "الأمان",
        newPassword: "كلمة سر جديدة",
        confirmPassword: "تأكيد كلمة السر",
        updateError: "حدث خطأ أثناء التحديث.",
        serverError: "خطأ في الخادم.",
        loadingProfile: "جاري تحميل الملف الشخصي...",
        searchMember: "البحث عن عضو...",
        noUserFound: "لم يتم العثور على مستخدم",
        startConversation: "ابدأ محادثة مع",
        typeMessage: "اكتب رسالتك...",
        internalMessaging: "المراسلة الداخلية",
        selectMemberToChat: "اختر عضواً من القائمة لبدء المحادثة.",
        seen: "تمت المشاهدة",
        sent: "تم الإرسال",
        reclamationsTitle: "الطلبات والشكاوى (الزوار)",
        noReclamations: "لا توجد شكاوى أو طلبات شراكة حالياً.",
        subjectInfo: "طلب معلومات",
        subjectPartnership: "اقتراح شراكة",
        subjectComplaint: "شكوى / تظلم",
        newBadge: "جديد",
        markAsRead: "تحديد كمقروء",
        delete: "حذف",
        receivedOn: "تم الاستلام في",
        replyByEmail: "الرد عبر البريد الإلكتروني",
        usersManagementTitle: "إدارة المستخدمين",
        selectAll: "تحديد الكل",
        deselectAll: "إلغاء تحديد الكل",
        exportExcel: "تصدير Excel",
        registeredOn: "عضو منذ",
        userDetails: "تفاصيل العضو",
        positionClub: "المنصب في النادي",
        adminNewPassword: "كلمة سر جديدة",
        leaveToKeepSame: "اتركه فارغاً للاحتفاظ بالحالية",
        notAuthorizedRoleChange: "ليس لديك صلاحية لتغيير الأدوار.",
        member: "عضو",
        role: "الدور",
        payment: "الدفع",
        phone: "الهاتف",
        status: "الحالة",
        paid: "تم الدفع",
        notPaid: "لم يتم الدفع",
        pending: "قيد الانتظار",
        approved: "مقبول",
        rejected: "مرفوض",
        confirmDeleteUser: "هل تريد حذف هذا المستخدم؟",
        partnersManagementTitle: "إدارة الشركاء",
        newPartner: "شريك جديد",
        confirmDeletePartner: "حذف هذا الشريك؟",
        editPartner: "تعديل الشريك",
        partnerName: "اسم الشريك",
        websiteOptional: "الموقع الإلكتروني (اختياري)",
        displayOrder: "ترتيب العرض",
        active: "نشط",
        partnerLogo: "شعار الشريك",
        chooseLogo: "اختر شعاراً",
        visitWebsite: "زيارة الموقع",
        order: "الترتيب",
        inactive: "غير نشط",
        clubsManagementTitle: "إدارة النوادي",
        newClub: "نادي جديد",
        editClub: "تعديل النادي",
        confirmDeleteClub: "هل تريد حذف هذا النادي؟",
        clubName: "اسم النادي",
        slugLabel: "الرابط (مثال: theatre-club)",
        description: "الوصف",
        addressLocal: "العنوان / المقر",
        socialLinks: "شبكات التواصل الاجتماعي",
        selectPresident: "اختر رئيساً",
        activeMembersLabel: "الأعضاء النشطون",
        partnerReviewsLabel: "آراء الشركاء",
        coverImage: "صورة الغلاف",
        chooseImage: "اختر صورة",
        uploading: "جاري الرفع...",
        update: "تحديث",
        createClub: "إنشاء النادي",
        manageMyPage: "إدارة صفحتي",
        identityDescription: "الهوية والوصف",
        clubDescription: "وصف النادي",
        activeMembersOfMonth: "الأعضاء النشطون لهذا الشهر",
        selectMembersToHighlight: "اختر الأعضاء الذين تريد إبرازهم هذا الشهر.",
        addMember: "إضافة عضو",
        chooseMember: "اختر عضواً",
        roleOptional: "الدور (اختياري)",
        period: "الفترة",
        noFeaturedMembers: "لا يوجد أعضاء بارزون حالياً.",
        reviewsTestimonials: "الآراء والشهادات",
        addReview: "إضافة رأي",
        author: "المؤلف",
        organization: "المنظمة",
        reviewContent: "محتوى الرأي",
        saveAllChanges: "حفظ جميع التغييرات",
        savingChanges: "جاري الحفظ...",
        changesSaved: "تم حفظ التغييرات!",
        loadingMyClub: "جاري تحميل ناديك...",
        noClubAssigned: "لم يتم تعيين أي نادٍ لك من قبل المسؤول.",
        selectMember: "-- اختر --",
        actionsAttendance: "الأنشطة والحضور",
        newAction: "نشاط جديد",
        noActionsFound: "لم يتم العثور على أنشطة. أنشئ واحداً للبدء.",
        addFirstAction: "إضافة نشاطي الأول",
        confirmDeleteAction: "هل أنت متأكد من حذف هذا النشاط؟",
        manageAttendance: "إدارة الحضور",
        addAction: "إضافة نشاط",
        actionTitle: "عنوان النشاط",
        startDateLabel: "تاريخ البدء",
        startTimeLabel: "الوقت المحلي",
        creating: "جاري الإنشاء...",
        createAction: "إنشاء النشاط",
        actions: "الأنشطة",
        attendanceList: "قائمة الحضور",
        present: "حاضر",
        remark: "ملاحظة",
        noMemberFoundClub: "لم يتم العثور على أعضاء لهذا النادي.",
        detailsUpdated: "تم تحديث التفاصيل!",
        attendanceUpdated: "تم تحديث الحضور بنجاح!",
        actionNotFound: "النشاط غير موجود.",
        errorLoadingAction: "خطأ في تحميل النشاط.",
        addRemark: "أضف ملاحظة...",
        contentsEventsTitle: "المحتويات والفعاليات",
        noContentPublished: "لا يوجد محتوى منشور حالياً.",
        editContent: "تعديل المحتوى",
        newContent: "محتوى جديد",
        type: "النوع",
        event: "فعالية",
        formation: "تكوين",
        photoGalleryLabel: "صور / معرض",
        videoYoutube: "فيديو / يوتيوب",
        announcement: "إعلان",
        galleryPhotos: "معرض الصور",
        imagesImported: "صور تم استيرادها",
        clearAll: "مسح الكل",
        noPhotoSelected: "لم يتم اختيار صور",
        videoUrl: "رابط الفيديو",
        externalLink: "رابط خارجي",
        submitForValidation: "إرسال للمراجعة",
        contentUpdated: "تم تحديث المحتوى!",
        contentSubmitted: "تم إرسال المحتوى بنجاح!",
        uploadFailed: "فشل استيراد الملف.",
        waitUpload: "يرجى الانتظار حتى ينتهي رفع الصور.",
        cover: "الغلاف",
        import: "استيراد",
        at: "في",
        pollsModerationTitle: "مراجعة الاستطلاعات",
        manageMyPolls: "إدارة استطلاعاتي",
        validatePollsDesc: "مراجعة الاستطلاعات التي أنشأها الرؤساء",
        createPollsDesc: "أنشئ استطلاعات للتفاعل مع مجتمعك",
        createPoll: "إنشاء استطلاع",
        noPollFound: "لم يتم العثور على استطلاع",
        public: "عام",
        membersOnlyLabel: "الأعضاء",
        multiChoice: "خيارات متعددة",
        singleChoiceLabel: "خيار واحد",
        participants: "مشاركين",
        reject: "رفض",
        approve: "قبول",
        newPoll: "استطلاع جديد",
        question: "السؤال",
        descriptionOptional: "الوصف (اختياري)",
        options: "الخيارات",
        addOption: "إضافة خيار",
        targetAudience: "الجمهور المستهدف",
        allVisitors: "جميع الزوار",
        voteType: "نوع التصويت",
        singleChoiceOption: "خيار واحد فقط",
        multiChoiceOption: "يسمح بخيارات متعددة",
        submit: "إرسال",
        confirmDeletePoll: "هل تريد حذف هذا الاستطلاع نهائياً؟",
        national: "وطني",
        testimonialsTitle: "الآراء والشهادات",
        noTestimonials: "لا توجد شهادات حتى الآن.",
        confirmDeleteTestimonial: "حذف هذه الشهادة؟",
        approvedStatus: "موافق عليه",
        waitingStatus: "قيد الانتظار",
        pointsManagementTitle: "إدارة النقاط",
        pointsManagementDesc: "منح أو إزالة نقاط مكافأة لأعضاء ناديك.",
        searchMemberPlaceholder: "ابحث عن عضو بالاسم أو البريد الإلكتروني...",
        bonusPoints: "نقاط مكافأة",
        noMemberFound: "لم يتم العثور على عضو.",
        updateError: "خطأ في التحديث",
        technicalError: "خطأ تقني",
        notificationsTitle: "الإشعارات",
        markAllAsRead: "تعليم الكل كمقروء",
        loadingNotifications: "جاري تحميل الإشعارات...",
        errorLoading: "خطأ في التحميل",
        serverConnectionError: "خطأ في الاتصال بالخادم",
        retry: "إعادة المحاولة",
        noNotifications: "ليس لديك إشعارات في الوقت الحالي.",
        markAsRead: "تعليم كمقروء",
        viewDetails: "عرض التفاصيل",
        usersManagementTitle: "إدارة المستخدمين",
        confirmDeleteUser: "هل أنت متأكد من حذف هذا المستخدم؟",
        selectAll: "تحديد الكل",
        deselectAll: "إلغاء تحديد الكل",
        exportExcel: "تصدير إلى Excel",
        selectAtLeastOne: "يرجى تحديد مستخدم واحد على الأقل.",
        noClub: "بدون نادي",
        registeredOn: "مسجل في",
        role: "الدور",
        payment: "الدفع",
        phone: "الهاتف",
        phonePlaceholder: "رقم الهاتف...",

        // General
        loading: "جاري التحميل...",
        error: "خطأ",
        back: "رجوع",
        backToSite: "العودة للموقع",
        save: "حفظ",
        cancel: "إلغاء",
        edit: "تعديل",
        name: "الاسم",
        create: "إنشاء",
        optional: "اختياري",
        preview: "معاينة",
        contentModerationTitle: "مراجعة المحتوى",
        addEvent: "إضافة فعالية",
        content: "المحتوى",
        clubChef: "النادي / الرئيس",
        sharing: "مشاركة",
        approveAction: "قبول",
        refuseAction: "رفض",
        home: "الرئيسية",
        bestOff: "الأفضل",
        editContentTitle: "تعديل المحتوى",
        newContentTitle: "محتوى جديد",
        associateClub: "ربط بالنادي",
        selectClub: "اختر نادياً",
        refused: "مرفوض",
        photosSelect: "صور (اختر واحدة أو أكثر)",
        importPhotos: "استيراد صور",
        videoUrlYoutube: "رابط فيديو (يوتيوب)",
        externalLinkRegistration: "رابط خارجي / تسجيل",
        saveChanges: "حفظ التغييرات",
        createEvent: "إنشاء الفعالية",
        contentSavedSuccess: "تم حفظ المحتوى بنجاح!",
        confirmDeleteContent: "حذف هذا المحتوى نهائياً؟",
        actionsModerationTitle: "مراجعة الأنشطة والأخبار",
        manifestationPlan: "مخطط التظاهرة",
        addItem: "إضافة عنصر",
        globalDuration: "المدة الإجمالية",
        partsCount: "عدد الأجزاء",
        automaticOrdering: "ترتيب تلقائي",
        startTime: "البداية",
        endTime: "النهاية",
        durationMin: "المدة (دقائق)",
        pause: "استراحة",
        coffeeBreak: "استراحة قهوة",
        breakfast: "فطور الصباح",
        lunch: "غداء",
        dinner: "عشاء",
        remark: "ملاحظة",
        soiree: "سهرة",
        sleep: "نوم",
        conference: "مؤتمر",
        formation: "تكوين",
        dj_party: "حفلة DJ",
        spectacle: "عرض",
        speakerName: "المتحدث / المنشط",
        speakerPhoto: "صورة المتحدث",
        settingsTitle: "إعدادات الجمعية",
        nationalBoardTitle: "المكتب الوطني",
        newMember: "عضو جديد",
        confirmDeleteMember: "حذف هذا العضو من المكتب؟",
        editMember: "تعديل العضو",
        roleFunction: "الوظيفة / الدور",
        rolePlaceholder: "مثال: رئيس، كاتب عام...",
        memberPhoto: "صورة العضو",
        choosePhoto: "اختر صورة",
        addToBoard: "إضافة إلى المكتب",
        aboutManagement: "إدارة من نحن",
        aboutManagementTitle: "إدارة صفحة من نحن",
        newSection: "قسم جديد",
        confirmDeleteSection: "حذف هذا القسم؟",
        editSection: "تعديل القسم",
        objective: "هدف",
        domain: "مجال",
        value: "قيمة",
        icon: "أيقونة",
        images: "صور / معرض",
        imageLayout: "تخطيط الصور",
        layoutBottom: "أسفل",
        layoutTop: "أعلى",
        layoutLeft: "يسار",
        layoutRight: "يمين",
        layoutGrid: "شبكة",
        add: "إضافة",
        buttonText: "نص الزر (اختياري)",
        buttonLink: "رابط الزر (اختياري)",
        buttonTextPlaceholder: "مثال: انضم للمجموعة",
        footerManagement: "إدارة تذييل الصفحة",
        footerManagementDesc: "تخصيص المعلومات المعروضة في تذييل الموقع.",
        footerDescription: "الوصف / من نحن",
        footerDescriptionPlaceholder: "وصف موجز للجمعية...",
        addressLocal: "العنوان / المقر",
        socialLinks: "شبكات التواصل الاجتماعي",
        quickLinks: "روابط سريعة",
        text: "نص",
        ourLocations: "مواقعنا",
        noAddress: "العنوان غير متوفر",
        meetingTA: "اجتماع TA",
        createMeeting: "إنشاء اجتماع",
        scheduleMeeting: "جدولة اجتماع",
        meetingDateTime: "التاريخ والوقت",
        lateLimitMinutes: "حد التأخير (دقائق)",
        participants: "المشاركون",
        meetingLink: "الرابط",
        joinMeeting: "انضمام",
        noMeetings: "لا توجد اجتماعات مجدولة",
        meetingConfirmed: "تم إنشاء الاجتماع بنجاح!",
        meetingNotificationTitle: "اجتماع TA جديد",
        meetingNotificationMessage: "أنت مدعو للاجتماع: {title}",
        meetingSettings: "إدارة اجتماع TA",
        authorizedRoles: "الأدوار المصرح لها",
        authorizedUsers: "مستخدمون محددون",
        pointsAwarded: "تم منح نقطة الحضور!",
        directMeeting: "مباشر (فوري)",
        scheduledMeeting: "مجدول",
        selectClubs: "اختيار النوادي",
        selectMembers: "اختيار الأعضاء",
        meetingDeleted: "تم حذف الاجتماع",
        confirmDeleteMeeting: "هل تريد حذف هذا الاجتماع؟"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('fr'); // Default to fr for SSR
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
        const savedLang = localStorage.getItem('language');
        if (savedLang && ['fr', 'en', 'ar'].includes(savedLang)) {
            setLanguage(savedLang);
        }
    }, []);

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    useEffect(() => {
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    // Helper to translate dynamic strings containing "Touches D'Art" or "Club"
    const formatDynamicText = (text) => {
        if (!text) return "";
        if (language !== 'ar') return text;

        let formatted = text;
        // Replace "Touches D'Art" (case insensitive, handling various quotes)
        formatted = formatted.replace(/Touches D'Art/gi, "لمسات فنّية");
        formatted = formatted.replace(/Touches d'Art/gi, "لمسات فنّية");
        // Replace "Club" (case insensitive)
        formatted = formatted.replace(/Club/gi, "نادي");

        return formatted;
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t, formatDynamicText }}>
            <div style={{ visibility: mounted ? 'visible' : 'hidden' }}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
